### ISSUE TITLE
Ben bu kütüphaneyi NestedScrollView içerisinde kullanıyorum. StorylyView 'in nestedScroll özelliğini kapatmak istiyorum 

### ISSUE THREAD

**Issue by murat-aydin** [Netvent/storyly-mobile#1]
Kullandığım View yapı olarak NestedScrollView içerisinde yer alıyor. Bu yüzden StorylyView 'in nestedScrollEnabled 'ını false yapmak istiyorum. Bununla benim dışardan bunu disabled edebileceğim şekilde bi fonksiyon yazabilir misiniz?

**Comment by levent-oral** [comment]
- Bahsi gecen platform ve kullandiginiz Storyly SDK versiyon hakkinda bilgi verebilir misiniz?

- Kullanimi daha iyi anlamak adina, kod parcasi ve durumu anlatan ekran goruntusu kaydi atabilir misiniz?

**Comment by murat-aydin** [comment]
Android platformunda 0.0.18 storyly sdk versiyonunu kullanmaktayım.

<androidx.core.widget.NestedScrollView
        android:id="@+id/contentNSV"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:id="@+id/mainContainerLL"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical" >

            <com.appsamurai.storyly.StorylyView
                android:id="@+id/storyView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:nestedScrollingEnabled="false" />

        </LinearLayout>

    </androidx.core.widget.NestedScrollView>


StorylyView , NestedScrollView içerisinde yer alıyor. 
Storyly view içerisinde android:nestedScrollingEnabled="false" şeklinde düzenlesem bile malesef disabled etmiyor.

**Comment by levent-oral** [comment]
Durumu tekrar olusturmak adina, benzer bir yapida demo app olusturduk ve bir takim denemeler yaptik orada. Bulgularimizi paylasmak istiyorum. 

- StorylyView, ScrollView icinde akiskan bir sekilde 'scoll' edilebiliyor. Hiyerarsi sayesinde NestedScrollView icinde durma zorunlulugu yok, direkt RecyclerView kullaniminin aksine.
- StorylyView, NestedScrollView icinde 'scroll' akiskanliginda parent view adina sorun olabiliyor; fakat 'nestedScrollingEnabled' degiskenini 'false' yapmamiz bu durumu duzeltmedi. O nedenle sadece API ekleyerek bu durumun degisecegine ikna degiliz. 

- NestedScrollView icine koyma zorunlulugun yoksa, onun disinda bir View icine koyarak deenemen mumkun mu? 
- Yasadigin durumu daha detayli anlatman, karsilastigin sorunu tanimlaman ve ekran videosu paylasman mumkun mu?

**Comment by levent-oral** [comment]
Yasadigin sorunu tam olarak bilmedigimiz icin benzer durumlari olusturmak adina demo app olusturduk ve bir takim denemeler yaptik orada. Bulgularimizi paylasmak istiyorum.

- StorylyView, ScrollView icinde akiskan bir sekilde 'scroll' edilebiliyor. Hiyerarsi sayesinde NestedScrollView icinde durma zorunlulugu yok, direkt RecyclerView kullaniminin aksine.
- StorylyView, NestedScrollView icinde 'scroll' akiskanliginda parent view adina sorun olabiliyor; fakat 'nestedScrollingEnabled' degiskenini 'false' yapmamiz bu durumu duzeltmedi. O nedenle sadece API ekleyerek bu durumun degiseceginden emin degiliz.

- NestedScrollView icine koyma zorunlulugun yoksa, onun disinda bir View icine koyarak deenemen mumkun mu?
- Yasadigin durumu daha detayli anlatman, karsilastigin sorunu tanimlaman ve ekran videosu paylasman mumkun mu?

Senin icin de uygun olursa Hangouts vb platformlar uzerinden de konusabiliiriz; levent@appsamurai.com

**Comment by murat-aydin** [comment]
Hangoust üzerinden davet gönderdim

**Comment by levent-oral** [comment]
This issue has been fixed with version 0.0.19
