### ISSUE TITLE
Can Storyly be programmatically closed?

### ISSUE THREAD

**Issue by IAmKio** [Netvent/storyly-mobile#108]
Issue tracker is **ONLY** used help requests, questions etc.

**Environment / Set-up:**
Platform: React Native
Version: 1.10.0
Package: storyly-react-native

**Summary:**
We have an issue whereby when we handle our onClick events and open a webview, the webview always opens behind the story being displayed.

**Question:**
Is it possible to programatically close Storyly when it is displayed from the onClick callback handler?

Thank you!

**Comment by levent-oral** [comment]
Hello @IAmKio,

There is [close](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RNStoryly.js#L27) method to close active story screen programmatically. Moreover, there is [open](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RNStoryly.js#L18) method to open story screen, closed previously, programmatically. 

Thanks,

**Comment by IAmKio** [comment]
We're rocking and rolling - thank you @levent-oral 
cc: @divyaBacancy
