### ISSUE TITLE
Null safety error on build

### ISSUE THREAD

**Issue by Corepany** [Netvent/storyly-mobile#112]
We are using the latest version of the flutter which supports sound null safety. 

## Environment Details
**Storyly SDK Version:** ---
1.11.1
**Flutter SDK Version:** ---
2.2.2
Dart SDK : Dart SDK version: 2.13.3

## Expected Behavior
We should be able to build with null safety support

## Current Behavior
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:storyly_flutter

## Steps to Reproduce
Build the app with SDK above 2.2.1

**Comment by levent-oral** [comment]
Hello @Corepany, 

We've a plan to add null-safety on storyly_flutter package. It'll be available with the next release. We'll let you know when it's available. 

Thanks,

**Comment by levent-oral** [comment]
Hello @Corepany, 

We've published [storyly_flutter@1.12.0](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/CHANGELOG.md#1120) version to support nullability. Please check [storyly_flutter's pub.dev page](https://pub.dev/packages/storyly_flutter/versions) for `null safety` tag.

Thanks for the contribution!
