### ISSUE TITLE
Crash issue in SDK 1.11.1 in JDID

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#114]
Currently crash issue from Storyly in our APP accounted for more than 50% of all crashes. Please help to check and fix it as soon as possible, or it will affect the user experience of our APP.
 
[李澄锋_2021-06-18 20 09 21.txt](https://github.com/Netvent/storyly-mobile/files/6747783/_2021-06-18.20.09.21.txt)

---java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
android.view.ViewGroup.addViewInner(ViewGroup.java:5274)
android.view.ViewGroup.addView(ViewGroup.java:5089)
android.view.ViewGroup.addView(ViewGroup.java:5029)
android.view.ViewGroup.addView(ViewGroup.java:5002)
com.appsamurai.storyly.storylypresenter.storylylayer.ae.a(StorylyLayerContainerView.kt:322)
com.appsamurai.storyly.storylypresenter.storylylayer.ae.a(StorylyLayerContainerView.kt:22)
com.appsamurai.storyly.storylypresenter.storylylayer.ae.a(StorylyLayerContainerView.kt:2)
com.appsamurai.storyly.storylypresenter.storylylayer.y.invoke(StorylyLayerContainerView.kt:1)
com.appsamurai.storyly.storylypresenter.storylylayer.ab$a$a.onResourceReady(StorylyImageView.kt:2)
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:622)
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:237)
android.app.ActivityThread.main(ActivityThread.java:7817)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

![image](https://user-images.githubusercontent.com/58552069/124118734-3a261c80-daa4-11eb-8027-3b47520b70b4.png)

![image](https://user-images.githubusercontent.com/58552069/124118747-401bfd80-daa4-11eb-8783-d5b41e775781.png)

![image](https://user-images.githubusercontent.com/58552069/124118753-4316ee00-daa4-11eb-9bb2-31962916e2ce.png)

![image](https://user-images.githubusercontent.com/58552069/124118763-46aa7500-daa4-11eb-990c-847f75b3daf9.png)

**Comment by levent-oral** [comment]
Hello @charischung ,

We're focusing on `java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.` issue as you specified explicitly. We're checking possible scenarios to reproduce the issue. There is a similar issue, #107. 

Are you able to give any steps to reproduce case or story group/story information that users encounter the issue? 

Thanks,

**Comment by levent-oral** [comment]
@charischung , the error in latest screenshot has been already reported in #111 , we're focusing on these 2 issues.

**Comment by charischung** [comment]
Actually this is the crash record from our APP, our user just view the Storyly page then APP crash.

**Comment by levent-oral** [comment]
Hello @charischung ,

We've made a fix for this issue in [Android SDK 1.13.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1130). Please check with that.

Especially, `IllegalStateException` and `IndexOutOfBoundException` handling have been improved in that version.

Thanks,
