### ISSUE TITLE
Story layout is broken on iPad

### ISSUE THREAD

**Issue by shmakovigor** [Netvent/storyly-mobile#119]
Story layout is broken when running on iPad in split or slide-over mode. Black screen when slide-over (looks like story is off-screen) and partially visible when in split mode.  Please see attached screenshots. Looks ok when running in full-screen mode. Window size should be respected instead of screen size.

![1](https://user-images.githubusercontent.com/10052224/124971129-8091f300-e031-11eb-9e9f-128fa29cfe16.png)
![2](https://user-images.githubusercontent.com/10052224/124971137-838ce380-e031-11eb-95db-2b0014a19c51.png)

## Environment Details
**Storyly SDK Version:** 1.11.1
**iOS SDK Version:** 14.5.1
**Device Model:** iPad Pro (12.9-inch)
**Device OS Version:** iPadOS 14.5.1

## Expected Behavior
Story should be displayed correctly when app running in different iPad modes (split or slide-over).

## Current Behavior
The story layout is broken when running on iPad in split or slide-over mode.

**Comment by levent-oral** [comment]
Hello @shmakovigor ,

We've added to the plan for upcoming releases for better iPad support. 

We'll let you know when it's released.

Thanks,

**Comment by levent-oral** [comment]
Hello @shmakovigor ,

We've made improvements for Split Mode handling in iPad devices in [Storyly iOS SDK 1.13.2](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1132-02082021) Story is shown in correct sized area but size changes when story open is not handled yet. 

Please check with this version and let us know if you have any further observations or suggestions for this improvement.

Thanks,
