### ISSUE TITLE
Turn off rtl support by default

### ISSUE THREAD

**Issue by indrih17** [Netvent/storyly-mobile#124]
If the application has `android:supportsRtl="false"`, ` textAlignment` == `gravity`. Therefore, when we set `textAlignment=center` in the admin panel, in the application we see it as `textAlignment=start`. 
We spent 5 fucking hours figuring out that the problem is you, not us. No need to force all applications to support RTL. Who wants to, he will turn it on.

**Comment by levent-oral** [comment]
Hello @indrih17 ,

We've made improvements for handling RTL disabled/enabled cases in [Storyly Android SDK 1.13.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1132-02082021).

It seems that [View#setTextAlignment](https://developer.android.com/reference/android/view/View#setTextAlignment(int)) usage for text alignments can cause problems with RTL disabled/enabled cases but there is no clear indication on Android docs. 

Please check this version for text alignment issue.

Thanks,
