### ISSUE TITLE
Small height problems: iOS circles overflow, Android circle containers remain

### ISSUE THREAD

**Issue by arutkayb** [Netvent/storyly-mobile#14]
![image](https://user-images.githubusercontent.com/22365448/81379682-3b62f000-9112-11ea-8ca1-263ba509f550.png)

**Comment by levent-oral** [comment]
Hi @arutkayb,

We've published 1.8.0 version of storyly_flutter package. This version brings new features with updated native sdk's.

This package contains improvements on size management. 

Thanks,
