### ISSUE TITLE
Story is just a black screen

### ISSUE THREAD

**Issue by yasincidem** [Netvent/storyly-mobile#140]
One of our users having an issue with stories. The issue is the black screen of any stories. I couldn't reproduce that and wanted to ask for help. 

Is this a known issue? 
Could it be just the case of this particular device?
Can we be sure it will be fixed with the latest version?

## Environment Details
**Storyly SDK Version:**  1.15.1
**Device Model:** JAT-L41
**Device OS Version:** 9

<img src="https://user-images.githubusercontent.com/13544246/141128511-849ca47d-1114-4ea7-91b2-0365efafead6.png" width="50%">

**Comment by levent-oral** [comment]
Hello @yasincidem,

We're investigating this issue for possible cases because it's not reproducible for our end. Do you think that it's related the media, is there any change on your side with uploaded media? (Asking just to get a clue) 

This could be related network condition at that moment. We're checking with throttled or unavailable network cases. 

Like you mentioned, it may be related with device but this is unlikely. Yet, one of the possibilities. 

Thanks,

**Comment by marcosluizss** [comment]
Hi @levent-oral,

 Occurred the same error on our app. 
 Some informations:
   - Initially, the error occurred on a story with video content. ( we're getting more information with the user ) 
   - When not have network access the loading animation is displayed
   - Not all device occurred the error, we tested with some and didn't happen the error 
 
Environment Details
- ** Device Model**: Samsung A20s
- **OS**: Android 10
- **Storyly SDK**: 1.13.1

You have some update for this issue?

**Comment by yasincidem** [comment]
Also, SM-G611F device has this issue. I couldn't reproduce this issue but our users occasionally ask about this.

**Comment by levent-oral** [comment]
@yasincidem , @marcosluizss ,

We'll check with these devices. 

Please check with latest version because we've improvements on playback side as well, [Android SDK 1.18.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1180-18112021)

**Comment by marcosluizss** [comment]
@levent-oral We've updated the storyly version in our app to version 1.18.2 and it's going into production throughout the week. We'll ask the user to retest and see if the issue is resolved and send you feedback.

**Comment by marcosluizss** [comment]
@levent-oral With the update, the operation for our user is back to normal, thank you.

**Comment by roshaan-sadapay** [comment]
We are also facing the same issue. All stories are black. Device details are below.

Android device: Redmi Note 8
Android OS version: 10

**Comment by roshaan-sadapay** [comment]
@levent-oral any update?
