### ISSUE TITLE
override fun storylyLoaded callback is called twice after initialization.

### ISSUE THREAD

**Issue by sergyabanzhy** [Netvent/storyly-mobile#143]
The issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version:*1.17.0*
**Android SDK Version:*Any*
**Device Model:*Any* ---
**Device OS Version:*Any*
**Additional Info:*Any*

## Expected Behavior
The callback should be invoked only once when stories became ready to be shown. Or there are some other reasons to call it twice?

## Current Behavior
The callback below every time is called twice
```
override fun storylyLoaded(
                    storylyView: StorylyView,
                    storyGroupList: List<StoryGroup>
                )
```

**Comment by levent-oral** [comment]
Hello @sergyabanzhy ,

There is a cache flow in Storyly data management to show stories quickly, so there could be several sources of data that is loaded. Please check [storylyLoaded event integration docs](https://integration.storyly.io/android/event-handling.html#storylyloaded-event) with [Storyly Android SDK 1.18.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1180-18112021) to distinguish events better.

Thanks,
