### ISSUE TITLE
I upgraded the version to 1.18.0, now the storyGroupList is empty in the 'storylyLoaded' method.

### ISSUE THREAD

**Issue by muhammedelsami** [Netvent/storyly-mobile#144]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version: 1.18.0
**Android SDK Version:any
**Device Model: any
**Device OS Version: any
**Additional Info: any

## Expected Behavior
storyGroupList should not be empty in 'storylyLoaded' method

## Current Behavior
I upgraded the version to 1.18.0, now the storyGroupList is empty in the 'storylyLoaded' method.

**Comment by levent-oral** [comment]
Hello @muhammedelsami ,

We've changed signature of storylyLoaded method to inform about source of data, [Storyly Android SDK 1.18.0](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1180-18112021). Can you check `dataSource` field for empty storyGroupList case? For example, one of the possibilities is `local`, Storyly data comes from local cache which could be empty for refresh install. 

Please refer usage of updated `storylyLoaded` in [storylyLoaded event documentation](https://integration.storyly.io/android/event-handling.html#storylyloaded-event).

Thanks,

**Comment by muhammedelsami** [comment]
Hi levent,
we changed the signature of storylyLoaded but we still get the same StoryGroupList as empty.

Thanks.

**Comment by levent-oral** [comment]
Does empty data comes with all possible data sources; `local`, `api` and `cdn`. Can you check accordingly please?

**Comment by muhammedelsami** [comment]
@levent-oral  yes it is empty from local and api.

**Comment by muhammedelsami** [comment]
current StorylyLoaded :

@Override
public void storylyLoaded(@NonNull StorylyView storylyView, 
                          @NonNull List<StoryGroup> storyGroupList,
                          @NonNull StorylyDataSource dataSource) {}

**Comment by levent-oral** [comment]
@muhammedelsami , that's correct one assuming formatting of `nonnull` and `override` are affected from formatting in Github :) 

We've checked with [Storyly Demo Java Project](https://github.com/Netvent/storyly-mobile/tree/master/android/java/StorylyDemo) using Storyly SDK 1.18.0 as well; data size is greater than 0 and isEmpty() function returns false. Can you check with it as well so we can have a reproduce case to understand the scenario? 

Is there a `segment` usage that can affect data's state?

**Comment by muhammedelsami** [comment]
@levent-oral  We are checking it out, thank you for your interest.

**Comment by muhammedelsami** [comment]
hi @levent-oral,
We do not use a segment that can affect the state of the data,
do we need to do anything on the dashboard in this update??

**Comment by levent-oral** [comment]
@muhammedelsami, no need to update anything on dashboard. 

We've checked with several scenarios, this issue is not reproducible. Can you open a PR to [Storyly Demo Java project](https://github.com/Netvent/storyly-mobile/tree/master/android/java/StorylyDemo) which issue is reproducible?

**Comment by levent-oral** [comment]
@muhammedelsami ,

We've made a fix in [Storyly Android SDK 1.18.1](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1181-26112021). 

Thanks,

**Comment by muhammedelsami** [comment]
bug was fixed in version 1.18.2, 

thanks.
