### ISSUE TITLE
Xcode 42 warning (Umbrella header for module 'Storyly' does not include header '...')

### ISSUE THREAD

**Issue by iTarek** [Netvent/storyly-mobile#145]
Xcode 42 warning (Umbrella header for module 'Storyly' does not include header '...')

Using cocoapods to install the SDK

## Environment Details
**Storyly SDK Version:** 
Storyly (1.18.0)

![Screen Shot 2021-11-25 at 6 33 53 PM](https://user-images.githubusercontent.com/693715/143478222-29683dea-3d24-4765-b098-32da6a33db43.png)

**Comment by levent-oral** [comment]
Hello @iTarek ,

Thanks for reporting, appreciate the effort!

We're aware of the warning. First of all, it's not required to include all headers so there is only warning for this. However, we're working on silencing these warnings. 

Thanks,

**Comment by mathaeus** [comment]
hey, we're also seeing those warnings and it's adding quite some noise to the CI logs. Any update on this @levent-oral ?

**Comment by mathaeus** [comment]
bump

**Comment by levent-oral** [comment]
This is not a stale ticket :) We're checking for the solution and its affects 👍

**Comment by levent-oral** [comment]
We've released [Storyly iOS SDK 1.21.0](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1210-1442022) version. This version contains improvements related to SDWebImage library usage.
