### ISSUE TITLE
Unresolved reference: setStoryGroupTextColor

### ISSUE THREAD

**Issue by LiyaYe** [Netvent/storyly-mobile#147]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

Cannot build Android

We cannot release new Android versions of our app, as a result from the build failure.

## Environment Details
**Storyly SDK Version:** "storyly-react-native": "^1.18.0" (latest)
**Android SDK Version:** 30
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:** build.gradle dependencies contains `classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30")`

## Expected Behavior
Android should build

## Current Behavior
Getting an error 
`> Task :storyly-react-native:compileDebugKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/liyayehu/.gradle/caches/transforms-3/6cffeab277090b874b00f106c26b2345/transformed/jetified-kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    /Users/liyayehu/.gradle/caches/transforms-3/8613c62f5a77efa7e1a2a249680aa275/transformed/jetified-kotlin-stdlib-jdk7-1.4.20.jar (version 1.4)
    /Users/liyayehu/.gradle/caches/transforms-3/1b15e87e10e213e70f17a0c9fe05c5d3/transformed/jetified-kotlin-stdlib-1.5.31.jar (version 1.5)
    /Users/liyayehu/.gradle/caches/transforms-3/d16a845f687310913e9ed56620a5ec5d/transformed/jetified-kotlin-stdlib-common-1.5.31.jar (version 1.5)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
432 actionable tasks: 5 executed, 427 up-to-date
Picked up JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
e: /Users/liyayehu/Documents/GitHub/fy-core/lib/app/node_modules/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt: (164, 26): Unresolved reference: setStoryGroupTextColor

FAILURE: Build failed with an exception.`

## Steps to Reproduce

1. executing `./gradlew build` on a project containing storyly 1.18.0

**Comment by levent-oral** [comment]
Hello @LiyaYe ,

We've released [storyly-react-native@1.18.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1181-612022) to fix this issue. 

Thanks,

**Comment by wass08** [comment]
Fixed the issue for me, thank you !
