### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#149]
Issue tracker is **ONLY** used suggestions.

Could not find a declaration file for module 'storyly-react-native'.

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We currently do not have any plans to add TypeScript, please feel free to contribute storyly-react-native plugin. You can find [storyly-react-native source code](https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native) here.

Thanks!

**Comment by makarkotlov** [comment]
Hi @levent-oral ,

I opened pr here https://github.com/Netvent/storyly-mobile/pull/156

**Comment by levent-oral** [comment]
Thanks @makarkotlov! 

It will be available with next release.

**Comment by levent-oral** [comment]
We've released [storyly-react-native@1.20.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1200-2232022) contains TypeScript support. 

Thanks for the contribution! 🎉
