### ISSUE TITLE
Swipe doesn't work on iOS

### ISSUE THREAD

**Issue by arutkayb** [Netvent/storyly-mobile#15]
On iOS, swipe doesn't open the Navigated page until all the story groups finished playing. I'm catching the callback and doing Navigate.push.

**Comment by uokesita** [comment]
I can confirm the Swipe Up does not work https://share.getcloudapp.com/kpu5pZgj

**Comment by levent-oral** [comment]
Hi @arutkayb,

We've published 1.8.0 version of storyly_flutter package. This version brings new features with updated native sdk's.

Please call storylyViewController's storyDismiss function to dismiss story screen and navigate accordingly.

Thanks,
