### ISSUE TITLE
React 17 and React Native 0.66 support

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#150]
Issue tracker is **ONLY** used suggestions.

npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project

npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from storyly-react-native@1.18.1

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We currently do not have any plans to update React/React-Native version, please feel free to contribute storyly-react-native plugin. You can find [storyly-react-native source code](https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native) here.

Thanks!
