### ISSUE TITLE
Android build failed React Native 0.67.1

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#151]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

* What went wrong:
A problem occurred evaluating project ':storyly-react-native'.
> Plugin with id 'maven' not found

* What went wrong:
A problem occurred configuring project ':storyly-react-native'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

I can't use the library. I'm trying to set up storyly.

## Environment Details
**Storyly SDK Version:** 1.19.0
**React Native SDK Version:** 0.67.1
**Platform:** Android
**Device Model:** Pixel 5 API 30 Emulator
**Device OS Version:** 30
**Additional Info:**

## Expected Behavior

Project build succeeded

## Current Behavior

Project build failed

## Steps to Reproduce

1. Set up fresh react native project
2. Set up storyly sdk according to documentation
3. npm run android

**Comment by levent-oral** [comment]
Hello @makarkotlov,

We've already defined [compiledSdkVersion](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/android/build.gradle#L45) in `build.gradle` file of project's android part. 

We've checked the error for possible scenarios, it may be related with Gradle version of project. We're using [Gradle@6.9.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/android/gradle/wrapper/gradle-wrapper.properties#L3) for our StorylyDemo project. Can you provide your version?

Thanks,

**Comment by makarkotlov** [comment]
RN 0.67.1 uses gradle-7.2

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We've released [storyly-react-native@1.20.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1200-2232022) package. We've updated Android setup using [ReactNative Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.67.3). 

We've tested with Gradle 7.0.4 as well.

Thanks!
