### ISSUE TITLE
Flags storyHeaderTextIsVisible and storyHeaderIconIsVisible have no effect

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#157]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

`storyHeaderTextIsVisible={false}` and `storyHeaderIconIsVisible={false}` are supposed to hide header text and header icon inside a story view, but they don't do that.

I want to hide header text and header icon inside a story view.

## Environment Details
**Storyly SDK Version:** 1.19.0
**React Native SDK Version:** 0.64.2, 0.66.2
**Platform:** Android, iOS
**Device Model:** iPhone 12 Pro Max, Huawei P20 Pro
**Device OS Version:** EMUI 10.0, iOS 15.1.1
**Additional Info:**

## Expected Behavior

Header text and header icon should be hidden inside a story view when `storyHeaderTextIsVisible` and `storyHeaderIconIsVisible` are both set to false

## Current Behavior

Header text and header icon are not hidden inside a story view when `storyHeaderTextIsVisible` and `storyHeaderIconIsVisible` both set to false

## Steps to Reproduce

1. `git clone git@github.com:Netvent/storyly-mobile.git`
2. `cd storyly-mobile/react-native/storyly-react-native/StorylyDemo/`
3. `yarn`
4. `cd ios && pod install && cd..`
5. Add `storyHeaderTextIsVisible={false}` and `storyHeaderIconIsVisible={false}` to Storyly in App.js
6. `yarn ios`
7. `yarn android`

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

It's required to give all of the header related stylings to see the affect. For your scenario; adding [storyHeaderTextIsVisible={false}](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RNStoryly.js#L140) will solve the problem. You can check the bridge parts for details; [Android Bridge](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt#L233) and [iOS Bridge](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/ios/RCTConvert%2BStoryly.m#L123).

We consider the change this implementation for next releases but current versions requirement is to provide all values.

Thanks,

**Comment by makarkotlov** [comment]
hi @levent-oral ,

I suppose you mean I should add [storyHeaderCloseButtonIsVisible={false}](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RNStoryly.js#L142) (not storyHeaderTextIsVisible, because I mentioned it in the title and in the description to this issue).

Even if that is the case and I will add all of the header related stylings (storyHeaderTextIsVisible={false}, storyHeaderIconIsVisible={false} and storyHeaderCloseButtonIsVisible={false}):
1. On Android there will be no story header icon, no close button and no text. But I need close button to stay visible.
2. On iOS there will be no effect at all.

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We've released [storyly-react-native@1.20.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1200-2232022) package. We've removed providing all value constraint for ui customizations. Please check with latest package.

Thanks,
