### ISSUE TITLE
Storyly doesn't work with landscape orientation on android

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#159]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

Stories don't respond to touch events when in landscape orientation.

I want storyly to be able to open stories in landscape orientation. It would be also great if storyly would be able to lock portrait orientation when story is opened and unlocking it when the story is closed.

## Environment Details
**Storyly SDK Version:** 1.19.0
**React Native SDK Version:** 0.64.2
**Platform:** Android
**Device Model:** Huawei P20 Pro, emulators
**Device OS Version:** android 10
**Additional Info:**

## Expected Behavior

User should open stories while in landscape orientation, locking portrait mode when a story is opened and unlocking it when the story is closed.

## Current Behavior

Storyly doesn't work with landscape orientation

## Steps to Reproduce

1. `git clone git@github.com:Netvent/storyly-mobile.git`
2. `cd storyly-mobile/react-native/storyly-react-native/StorylyDemo/`
3. `yarn`
4. `yarn android`
5. Change device orientation to landscape
6. Try to open the story

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We've observed a case with opening story in landspace orientation. 

Change orientation to landspace from portrait and click a story group in storyly bar to open a story; observe that story doesn't open. Is this your case or is there any other cases for orientation changes? 

Thanks!

**Comment by makarkotlov** [comment]
Hi @levent-oral ,

That's all. In addition there would be great to force portrait mode when opening a story.

**Comment by makarkotlov** [comment]
Hi @levent-oral,

I see that in version 1.20.0 there is a change of this behaviour. Now if I tap a story group the portrait mode is forced, but a story is not opened, so I need to tap it again. It would be great if you could fix it. Thank you!
