### ISSUE TITLE
Swipe up doesn't work on Android

### ISSUE THREAD

**Issue by arutkayb** [Netvent/storyly-mobile#16]
On iOS, swipe doesn't open the Navigated page until all the story groups finished playing. I'm catching the callback and doing Navigate.push.

**Comment by uokesita** [comment]
Indeed "Swipe Up" does not work https://share.getcloudapp.com/kpu5pZgj

**Comment by levent-oral** [comment]
Hi @arutkayb,

We've published 1.8.0 version of storyly_flutter package. This version brings new features with updated native sdk's.

Please call `storylyViewController`'s `storyDismiss` function to dismiss story screen and navigate accordingly.

Thanks,
