### ISSUE TITLE
Conflicting issue of Storyly with SDWebImage.

### ISSUE THREAD

**Issue by AbidBhatti** [Netvent/storyly-mobile#161]
Hi, I have Storyly and SDWebImage dependencies installed in my Xcode project using cocoapods.

Earlier Storyly used to have SDWebImage dependency but in version 1.18.0 this is removed. (And also added SDWebImage classes in Storyly framework).

I have updated Storyly version to latest and now Storyly and SDWebImage pods are conflicting because both are having same properties but with different type. 

In Storyly it seems that same classes has been used but with a different names for example - **SDWebImage** has a class name **SDWebImageActivityIndicator** and **Storyly** has a class name **ST_SDWebImageIndicator** but the property I want to use has same name in both dependencies that is - `myImageView.sd_imageIndicator`

So now if I do something like this -
`myImageView.sd_imageIndicator = SDWebImageActivityIndicator.gray`
It gives me an error.
`Cannot assign value of type 'SDWebImageActivityIndicator' to type 'ST_SDWebImageIndicator?.`

<img width="549" alt="Screenshot 2022-02-07 at 7 46 11 PM" src="https://user-images.githubusercontent.com/63389659/153213477-e135ebe8-b731-4165-81a2-27fe3311adf2.png">

**Comment by levent-oral** [comment]
Hello @AbidBhatti ,

We reproduced the issue. We'll release a patch version to fix this issue. We'll inform you.

Thanks,

**Comment by levent-oral** [comment]
We've released [Storyly iOS SDK 1.21.0](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1210-1442022) version. This version contains improvements related to SDWebImage library usage.
