### ISSUE TITLE
Events are not triggering in react native.

### ISSUE THREAD

**Issue by siddhant-rigi** [Netvent/storyly-mobile#166]
I am trying to implement storyly in react-native, After implementing every thing and setting up story from dashboard, not receiving any event like 
` onLoad={storyGroupList => alert('[Storyly] onLoad')}
            onFail={errorMessage => console.log('[Storyly] onFail')}
            onStoryOpen={() => console.log('[Storyly] onStoryOpen')}
            onStoryClose={() => console.log('[Storyly] onStoryClose')}
            onPress={story => console.log('[Storyly] onPress')}
            onEvent={eventPayload => console.log('[Storyly] onEvent')}
            onUserInteracted={() => console.log('[Storyly] onUserInteracted')}`
    
    
 Events are triggering in kotlin I put the logs 
 storylyLoaded in that method and they are working fine. but in react native none of event is triggering.

**Comment by levent-oral** [comment]
Hello @siddhant-rigi ,

We've released [storyly-react-native@1.20.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1200-2232022) package. Please upgrade and let us know if issue persists.

Thanks,

**Comment by levent-oral** [comment]
We've investigated the issue, it seems that there could be conflicts with core-ktx library and compiled android sdk version. 

[StorylyDemo](https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native/StorylyDemo) setup works with latest version of [compiledSdkVersion=31](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/android/build.gradle#L7). Moreover, is there any code that forces using specific version of core-ktx. 

Check with [StorylyDemo](https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native/StorylyDemo) , a working setup, to investigate what could be the difference that leads to this issue. Especially, `compiledSdkVersion`, `targetSdkVersion`, `kotlinVersion` and `gradle-plugin` in [app's build.gradle](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/android/build.gradle)

**Comment by siddhant-rigi** [comment]
Versions 1.18.1 is working fine after.
 Here is mine buildScript
 ```

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        kotlinVersion = '1.5.0'
        ndkVersion = "20.1.5948944"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.2")
        classpath 'com.google.gms:google-services:4.3.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

```

**Comment by levent-oral** [comment]
Can you test it by upgrading related parts;
> `compileSdkVersion = 31`
> `targetSdkVersion = 31`
> `classpath('com.android.tools.build:gradle:7.0.4')`

Moreover, upgrading compiledSdkVersion=31 requires additional step in AndoidManifest.xml;

> add exported=true in MainActivity decleration; [exported=true](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/android/app/src/main/AndroidManifest.xml#L16)
