### ISSUE TITLE
[React Native] React 17 support

### ISSUE THREAD

**Issue by makarkotlov** [Netvent/storyly-mobile#171]
Issue tracker is **ONLY** used suggestions.

It seems that after upgrading React Native and React versions (closing [this](https://github.com/Netvent/storyly-mobile/issues/150) issue in consequence and updating package.json of the demo project [here](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/package.json)) the main [package.json](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/package.json) wasn't updated. And npm still throws an error that says that storyly needs React 16.8.1.

**Comment by levent-oral** [comment]
Hello @makarkotlov ,

We've updated React and ReactNative dependencies in [storyly-react-native@1.20.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1201-3132022) version. 

You can check [peerDependencies](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/package.json#L28).

Thank!
