### ISSUE TITLE
Updating the library to the latest version

### ISSUE THREAD

**Issue by yasincidem** [Netvent/storyly-mobile#178]
Hi, I am having difficulty to use the latest version of this library in an app with compileSdk and targetSdk set to 30. It's written **reduced compileSdk and targetSdk to 30** in changelog but I am getting this error. Does this library need to be compiled with the compileSdk version 31 anymore?

Besides it would be great to access to a sample that uses the latest version of the library.

![image](https://user-images.githubusercontent.com/13544246/165801830-4de936ac-3eb1-4d4e-910f-81c4e4a3ee4b.png)

https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1211-1642022

**Comment by levent-oral** [comment]
Hello @yasincidem ,

We prepared a [sample PR](https://github.com/Netvent/storyly-mobile/pull/176) to guide Android SDK 31 requirement handling. 

Thanks,
