### ISSUE TITLE
Dependency resolution & conflict with react-native-video: exoplayer

### ISSUE THREAD

**Issue by ofreyssinet-ledger** [Netvent/storyly-mobile#188]
Hello, I'm currently trying to integrate the `storyly-react-native` SDK in an app which also has `react-native-video` as a dependency.

The issue is that [`react-native-video` depends on `exoplayer:2.13.3`](https://github.com/react-native-video/react-native-video/blob/master/android-exoplayer/build.gradle#L36) while `storyly-react-native` depends on 2.17.1, so I get this error when I compile with no additional build configuration:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.1-runtime (com.google.android.exoplayer:exoplayer-core:2.17.1) and jetified-exoplayer-ui-2.13.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.13.3)
     Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.17.1-runtime (com.google.android.exoplayer:exoplayer-common:2.17.1) and jetified-exoplayer-ui-2.13.3-runtime (com.google.android.exoplayer:exoplayer-ui:2.13.3)
```

#### Option A: Force `exoplayer` to `2.17.1`:

The thing is if I force the `exoplayer` version to 2.17.1 (in `app/build.gradle`):

> ```
> implementation ('com.google.android.exoplayer:exoplayer:2.17.1')
> compile project(':storyly-react-native')
> implementation(project(path: ":react-native-video")) {
>     exclude (group: "com.google.android.exoplayer")
> }
> ```

the app builds fine but crashes at runtime as soon as the apps starts, when the `react-native-video` native package gets loaded:

> ```
> E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
> E AndroidRuntime: Process: com.ledger.live.debug, PID: 10632
> E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.brentvatne.exoplayer.ReactExoplayerViewManager: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext) failed to verify: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext): [0x4]  can't resolve returned type 'Reference: android.view.View' or 'Unresolved Reference: com.brentvatne.exoplayer.ReactExoplayerView' (declaration of 'com.brentvatne.exoplayer.ReactExoplayerViewManager' appears in /data/app/~~BwtO1QzqzS_G2hIXyMLc_A==/com.ledger.live.debug--RWNk3P62pHDeZ0PD71yMQ==/base.apk!classes10.dex)
> E AndroidRuntime:        at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
> E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:928)
> E AndroidRuntime:        at com.swmansion.reanimated.ReanimatedPackage.createUIManager(ReanimatedPackage.java:75)
> E AndroidRuntime:        at com.swmansion.reanimated.ReanimatedPackage.getModule(ReanimatedPackage.java:31)
> E AndroidRuntime:        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
> E AndroidRuntime:        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
> E AndroidRuntime:        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
> E AndroidRuntime:        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
> E AndroidRuntime:        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:175)
> E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:502)
> E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:478)
> E AndroidRuntime:        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
> E AndroidRuntime:        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
> E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1227)
> E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1172)
> E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:138)
> E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1125)
> E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
> E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
> E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
> E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
> E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
> E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
> E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
> ```

#### Option B: Force `exoplayer` to `2.13.3`:

Then if I force the `exoplayer` version to 2.13.3 like this:

> ```groovy
>  implementation ('com.google.android.exoplayer:exoplayer:2.13.3')
>  implementation (project(path: ':react-native-video')) {
>      exclude (group: "com.google.android.exoplayer") 
>  }
> ```
Then obviously it crashes as soon as we load a video story with this log:

> ```
> E AndroidRuntime: FATAL EXCEPTION: main
> E AndroidRuntime: Process: com.ledger.live.debug, PID: 11114
> E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;)V in class Lcom/google/android/exoplayer2/ExoPlayer$Builder; or its super classes (declaration of 'com.google.android.exoplayer2.ExoPlayer$Builder' appears in /data/app/~~Du_NCpjtvtoPOSBiK_ViTw==/com.ledger.live.debug-usRYOFBB3vfbyjMqtzrwLQ==/base.apk)
> E AndroidRuntime:        at com.appsamurai.storyly.storylypresenter.storylylayer.q.a(StorylyExoVideoView.kt:36)
> E AndroidRuntime:        at com.appsamurai.storyly.storylypresenter.storylylayer.w.invoke(StorylyLayerContainerView.kt:308)
> E AndroidRuntime:        at com.appsamurai.storyly.storylypresenter.storylylayer.b.a(LayerMetadataManager.kt:252)
> E AndroidRuntime:        at com.appsamurai.storyly.storylypresenter.storylylayer.b.b(LayerMetadataManager.kt:104)
> E AndroidRuntime:        at com.appsamurai.storyly.storylypresenter.storylylayer.x.run(View.kt:6)
> E AndroidRuntime:        at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
> E AndroidRuntime:        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
> E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3362)
> E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
> E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
> E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
> E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
> E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:780)
> E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
> E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
> E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
> E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
> E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
> E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
> E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```

I know that the issue is on `react-native-video` because it should actually support a higher version of exoplayer, but then **my main question is:** until `react-native-video` gets an update to support `exoplayer 2.17.1`, is there a way to use both `react-native-video` and  `storyly-react-native` (with video stories) in the same android app?
For instance is there an older version of `storyly-react-native` that works fine with exoplayer `2.13.3`?

**PS:**
[There is a PR on `react-native-video` to bump the exoplayer dependency](https://github.com/react-native-video/react-native-video/pull/2498
) and I seem to be lucky with the timing as it seems like it's about to get merged soon, which would hopefully solve this issue altogether.

## Environment Details
**Storyly SDK Version:** `storyly-react-native@1.23.1`
**Android SDK Version:**:
```
buildToolsVersion = "30.0.2"
minSdkVersion = 24
compileSdkVersion = 30
targetSdkVersion = 30
ndkVersion = "21.4.7075529"
kotlinVersion = "1.4.10"
androidXCore = "1.6.0"
```

**Device Model:** Android emulator Pixel 5 API
**Device OS Version:** Android API 32
**Additional Info:** ---

## Steps to Reproduce

Option B's source code is here https://github.com/LedgerHQ/ledger-live/commit/b7de7c3d3a3bd43085a5ca37615a76935aebe63a

**Comment by levent-oral** [comment]
Hello @ofreyssinet-ledger ,

We've removed ExoPlayer dependency from our project with [Storyly Android SDK 1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1241-23072022). [storyly-react-native@1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1241-31072022) uses this version of Storyly Android SDK.

Thanks!
