### ISSUE TITLE
In Latest Storyly SDK, text in Arabic get truncate sometimes and it dose not show the full text

### ISSUE THREAD

**Issue by iTarek** [Netvent/storyly-mobile#192]
Text in Arabic get truncate sometimes and it dose not show the full text (Starting from Storyly SDK Version 1.21.0) , this make stories unusual because user did not get the full information...

Storyly SDK Version: 1.23.2 (Starting from 1.21.0)
iOS SDK Version: iOS 15.5
Device Model: iPhone 12 Pro (Device Language is English)
Device OS Version: 15.5

## Expected Behavior
To see the full text

![Screen Shot 2022-06-23 at 3 07 21 PM](https://user-images.githubusercontent.com/693715/175306100-4ee74409-1527-46e2-8b2d-df445e6f7a96.png)

## Current Behavior
The Arabic text get truncate

![IMG_0998F3F8639C-1](https://user-images.githubusercontent.com/693715/175306127-43d0dd40-b3fa-45b7-8301-d515ebd6cabc.jpeg)
![IMG_39141B034AF3-1](https://user-images.githubusercontent.com/693715/175306156-e4908810-8a12-4977-b1d9-a4ef1eb3916e.jpeg)
![IMG_F5B460A1026D-1](https://user-images.githubusercontent.com/693715/175306176-bd5d6858-aa54-4df2-9571-cad4e30e0234.jpeg)

## Steps to Reproduce
I build my app with latest Storyly SDK (1.23.2) and see this bug on stories while run the TestFlight version and on the debug version from Xcode, I also tried every Storyly SDK release till I found that problem started from version (1.21.0)

This bug happens on the Storyly SDK version (1.21.0), it was good before that...The App Store version of my app works fine. because it have Storyly SDK version (1.20.2)
https://apps.apple.com/us/app/id362375140

Now I want to update and use the latest Storyly SDK but because of this bug I will wait your fix.

My Storyly account: info @ iPhoneIslam.com

**Comment by levent-oral** [comment]
Hello @iTarek ,

We've released [Storyly iOS SDK 1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1241-29072022) to fix this issue. 

Thanks!

**Comment by iTarek** [comment]
I can confirm it works good, Thank you.
