### ISSUE TITLE
Can't run gradle task assembleAndroidTest on React Native project

### ISSUE THREAD

**Issue by wass08** [Netvent/storyly-mobile#198]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

Can't run gradle task assembleAndroidTest on a project containing storyly-react-native library

Trying to setup E2E on my React Native project with detox and I need to be able to build the test apk but it fails because of missing compileOptions in the build.gradle

## Environment Details
**Storyly SDK Version:** 1.24.4
**React Native SDK Version:** 0.68.0
**Platform:**
- [x] Android 

## Expected Behavior
<img width="375" alt="image" src="https://user-images.githubusercontent.com/6551176/176381239-b627d230-df03-4e99-8b04-6a4b21cc25d8.png">

## Current Behavior
<img width="758" alt="image" src="https://user-images.githubusercontent.com/6551176/176381166-c52f4480-d0cd-401e-8d19-050bba9aaff1.png">

## Steps to Reproduce

1. `cd android; ./gradlew assembleAndroidTest; cd ..`

## How to fix
It just requires the compileOptions in the build.gradle to work, I will create a PR that fix the issue.

**Comment by levent-oral** [comment]
Hello @wass08 ,

Thanks for contribution! 🎉 

We've released [storyly-react-native@1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1241-31072022) that contains related changes.

Thanks!
