### ISSUE TITLE
iOS fail at build time

### ISSUE THREAD

**Issue by agent3bood** [Netvent/storyly-mobile#20]
I have added version 1.3.0 react-native, did pod install.
At build time on xCode I get this error
 `No visible @interface for 'StorylyView' declares the selector 'setExternalDataWithExternalData:''`
this is in `storyly-react-native/STStorylyView.m` line 57
xCode version 11.3.1
react-native 0.61.5

**Comment by agent3bood** [comment]
The current pod version 1.3.2 is causing the build to fail, this version has breaking changes according to this https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md

**Comment by levent-oral** [comment]
Hi @agent3bood ,

This issue has been fixed with storyly-react-native@1.3.1 version. 

Thanks!

**Comment by agent3bood** [comment]
Thanks for the quick fix.
