### ISSUE TITLE
Typing for `openStoryWithId` doesn't match iOS method signature (`NSNumber` expected, `string` in TypeScript)

### ISSUE THREAD

**Issue by ofreyssinet-ledger** [Netvent/storyly-mobile#201]
The typing for `openStoryWithId` doesn't match the method signature of the iOS native module (`NSNumber` expected, `string` in TypeScript):

[`index.d.ts`](https://github.com/Netvent/storyly-mobile/blob/f5e8bf33fc7aac91849e4edd022096c155f99fd8/react-native/storyly-react-native/index.d.ts#L117)
```typescript
  export class Storyly extends Component<Storyly.Props> {
    // ...
    openStoryWithId: (storyGroupId: string, storyId: string) => void;
  }
```

[`STStorylyManager.m`](https://github.com/Netvent/storyly-mobile/blob/f5e8bf33fc7aac91849e4edd022096c155f99fd8/react-native/storyly-react-native/ios/STStorylyManager.m#L61):
```objective-c
RCT_EXPORT_METHOD(openStoryWithId:(nonnull NSNumber *)reactTag
                  storyGroupId:(nonnull NSNumber *)storyGroupId
                  storyId:(nonnull NSNumber *)storyId)
{
// ...
}
```

Calling `openStoryWithId` on iOS with `storyGroupId` & `storyId` as strings will then result in a crash.
The workaround so far is to put a `// @ts-ignore` next to this line but this is not ideal.

## Environment Details
**Storyly SDK Version:** 1.23.4
**React Native SDK Version:** 0.67.3
**Platform:**
- [ ] Android 
- [x] iOS
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:**

## Expected Behavior
Calling `openStoryWithId` on iOS with `storyGroupId` & `storyId` as strings does not crash.

## Current Behavior
Calling `openStoryWithId` on iOS with valid `storyGroupId` & `storyId` as strings results in a crash.
Calling the same method with numbers, as expected by the iOS native module works fine.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by levent-oral** [comment]
Hello @ofreyssinet-ledger ,

Thanks for the effort on the issue description, appreciated! 🎉 

We released [storyly-react-native@1.24.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1240-08072022) to fix this issue. 

Thanks!
