### ISSUE TITLE
Opening a story with `openStoryWithId` on Android doesn't update the "seen" state of stories/storyGroups

### ISSUE THREAD

**Issue by ofreyssinet-ledger** [Netvent/storyly-mobile#202]
I'm using `openStoryWithId` to trigger the opening of a story using a custom UI.

It works fine but **the "seen" state of the stories doesn't get updated** (neither visibly in the `Storyly` component nor in the `handleLoad` or `handleEvent` callbacks where `seen` stays false for all stories and story groups).

On iOS it works as expected, not **on Android**

This is an issue as the UI doesn't reflect the actual state of things (the user has seen these stories / story groups)

## Environment Details
**Storyly SDK Version:** 1.23.4
**React Native SDK Version:** 0.67.3
**Platform:**
- [x] Android 
- [ ] iOS
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:**

## Expected Behavior

Using `openStoryWithId` on Android to trigger the opening of a story should update the "seen" state of the stories and story groups once the user has effectively seen them.

## Current Behavior

Using `openStoryWithId` on Android to trigger the opening of a story does not update the "seen" state of the stories and story groups once the user has effectively seen them.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by levent-oral** [comment]
Hello @ofreyssinet-ledger ,

Thanks for the effort on the issue description, appreciated! 🎉 

We'll release a patch to fix this issue, we'll let you know!

Thanks,

**Comment by levent-oral** [comment]
Hello @ofreyssinet-ledger ,

We've released [Storyly Android@1.24.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1242-29072022) that contains a fix for this issue. [storyly-react-native@1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1241-31072022) uses this version of Storyly Android SDK.

Thanks!
