### ISSUE TITLE
Arrow keys are blocking content of stories.

### ISSUE THREAD

**Issue by GalacticTitan** [Netvent/storyly-mobile#209]
I am attaching one screenshot below. So left and right arrow keys blocking story content.

![Screenshot_2022-08-08-14-43-40-147_com bedwal bijak mvp test](https://user-images.githubusercontent.com/17767418/183415909-c4acdb59-a854-4f7d-a15c-fb8173434184.jpg)

## Environment Details
**Storyly SDK Version:1.24.1** ---
**Flutter SDK Version:2.10.5** ---
**Platform:**
- [ x] Android
**Device Model:Redmi Note 9 pro** ---
**Device OS Version:Android 11** ---

**Comment by hmelihf** [comment]
Hello @GalacticTitan ,
Voiceover/talkback with enhanced text-to-speech is the main feature of visual interaction for the users that use accessibility features so direct text visibility is not a prioritized concern for those users. Storyly adds arrow keys in the center of the story area with this motivation.  Moreover, there is a story alt-text description area in the Storyly Studio for the content to provide voiceover/talkback features extendibility.
Thanks for the suggestion!
