### ISSUE TITLE
React Native - storylyUserProperty type mismatch

### ISSUE THREAD

**Issue by wass08** [Netvent/storyly-mobile#210]
The prop storylyUserProperty is defined as a `Record<string, string>[];` in TypeScript while the documentation says it's a`Map<String, String>` so we expect it to be a ` Record<string, string>
`

Passing userProperties doesn't work and lead to a crash as it does not expect an array of Records
<img width="399" alt="image" src="https://user-images.githubusercontent.com/6551176/183610046-e1597167-0c30-40f4-bcf7-23783cd9f70e.png">

## Environment Details
**Storyly SDK Version:** 1.24.1
**React Native SDK Version:** 0.68.0
**Platform:**
- [x] Android 
- [x] iOS

## Steps to Reproduce
1. Add storylyUserProperty props in a typescript react native app

**Comment by levent-oral** [comment]
Hello @wass08, 

We've released [storyly-react-native@1.26.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1260-24082022) that contains a fix for this issue.

Thanks,
