### ISSUE TITLE
Share feature is not working in 1.25.0

### ISSUE THREAD

**Issue by michal-kos-droids** [Netvent/storyly-mobile#213]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

## Environment Details
**Storyly SDK Version:** 1.25.0
**iOS SDK Version:** ---
**Device Model:** iPhone 13 Pro
**Device OS Version:** 15.5
**Additional Info:** ---

## Expected Behavior
After tapping share button, share sheet displays.

## Current Behavior
After a new update, sharing does not work on stories with sharing enabled. Button highlights, but nothing happens.

## Steps to Reproduce
1. Tap story
2. Tap share button

> 2022-08-16 08:28:18.168886+0200 CCC[25262:247806] [ShareSheet] connection invalidated

**Comment by levent-oral** [comment]
Hello @michal-kos-droids ,

We've released [Storyly iOS SDK 1.26.0](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1260-23082022) that contains a fix for this issue.

Thanks,
