### ISSUE TITLE
Share button is not working for Ios devices

### ISSUE THREAD

**Issue by GalacticTitan** [Netvent/storyly-mobile#219]
It is happening when we clicked on share button on stories. Happening only for IOS device. It was working on previous flutter version.

It is throwing following error:

**couldn't find entitlement CopresenceCore.Entitlement.publicAPI error nil**

Working version: storyly_flutter: 1.22.1
Bug found version: storyly_flutter: 1.24.1

## Expected Behavior
Share button should work properly

## Current Behavior
Share button is not clickable

## Steps to Reproduce

1. Click on story group
2. click on share button

**Comment by levent-oral** [comment]
Hello @GalacticTitan ,

We've released [storyly_flutter@1.26.0](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/CHANGELOG.md#1260-24082022) that contains a fix for this issue.

Thanks,
