### ISSUE TITLE
Is going to be possible in React native - Expo?

### ISSUE THREAD

**Issue by esuarezz** [Netvent/storyly-mobile#23]
I am curious about storyly, and I wanted to do a try.
I consider many of the MVP's or first stage products are done in Expo when we are building in react native, so it would be really nice to have this available.
For example, I was considering create a "Wall" with some short news but this would fit perfectly for example, also to add links to go to the website to check blog and get extra information,

Thanks,
Elio S

**Comment by levent-oral** [comment]
Hello @esuarezz ,

For now, expo support is not in the short time roadmap. We've considered it as well, but there are other features in the pipeline.
