### ISSUE TITLE
Value of type 'StorylyView' has no member 'storyGroupTextColor' in spm 1.27.1

### ISSUE THREAD

**Issue by saitcihaner** [Netvent/storyly-mobile#232]
Issue tracker is **ONLY** used help requests, questions etc.

Can someone help in this situation for solution?Thanks for eveything

**Comment by levent-oral** [comment]
Hello @saitcihaner ,

We've added new fields for text color customization to cover seen/unseen difference. Please check [Storyly iOS SDK 1.24.1](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1241-29072022) version's release notes.

Please check [Story Group Text Styling](https://docs.storyly.io/docs/ios-set-up-storyly-bar#story-group-text-styling) documentation for details, `storyGroupTextColorSeen` and `storyGroupTextColorNotSeen` fields.

Thanks,
