### ISSUE TITLE
Impossible to get the presented story with storylyStoryPresented

### ISSUE THREAD

**Issue by nicolas-besnard** [Netvent/storyly-mobile#24]
Hi,

Is there a way to get the presented story with `storylyStoryPresented`?

**Comment by levent-oral** [comment]
Hi @nicolas-besnard ,

We're not passing active Story data as parameter in `storylyStoryPresented`. Would you elaborate the need please? We want to understand your case correctly.

Thanks,

**Comment by nicolas-besnard** [comment]
Hi :)

It's mainly for external tracking purpose. For example, I want to be able to target people that didn't saw a specific story.

It would help to know when a specific story group is display, and which stories in the story group has been viewed.

**Comment by levent-oral** [comment]
Hi @nicolas-besnard ,

We've discussed this and we've decided that tracking using dashboard's analytics would be better. 

Moreover, `storylyStoryPresented` is called only start of preview session, not for each story impression.

Thanks,
