### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by yasinugrl** [Netvent/storyly-mobile#247]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

## Environment Details
**Storyly SDK Version:**  "storyly-react-native": "^1.27.0",
**React Native SDK Version:** "react-native": "0.64.2",
**Platform:**
- [ ] Android 
- [x ] iOS

## Current Behavior
When runing our pipeline for build app getting error. 

❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyManager.swift:20:21: value of type 'RCTBridge' has no member 'uiManager'

        self.bridge.uiManager.addUIBlock { uiManager, viewRegistry in
                                                           ^

❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyManager.swift:33:21: value of type 'RCTBridge' has no member 'uiManager'

        self.bridge.uiManager.addUIBlock { uiManager, viewRegistry in
        ~~~~~~~~~~~ ^~~~~~~~~



❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyManager.swift:46:21: value of type 'RCTBridge' has no member 'uiManager'

        self.bridge.uiManager.addUIBlock { uiManager, viewRegistry in
        ~~~~~~~~~~~ ^~~~~~~~~



❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyManager.swift:59:21: value of type 'RCTBridge' has no member 'uiManager'

        self.bridge.uiManager.addUIBlock { uiManager, viewRegistry in
        ~~~~~~~~~~~ ^~~~~~~~~



❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyManager.swift:71:21: value of type 'RCTBridge' has no member 'uiManager'

**Comment by levent-oral** [comment]
Hello @yasinugrl ,

We've released [storyly-react-native@1.27.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1271-10112022) version that contains the fix for this issue.

Thanks,
