### ISSUE TITLE
Build iOS App with you RN SDK

### ISSUE THREAD

**Issue by yasinugrl** [Netvent/storyly-mobile#256]
Issue tracker is **ONLY** used for reporting React Native SDK related bugs.

Storyly SDK Version: "storyly-react-native": "^1.29.0",
React Native SDK Version: "react-native": "0.64.2",

**Platform:**
- [ ] Android 

## Current Behavior

When build app getting this error from your library.

❌  /Users/runner/work/1/s/node_modules/storyly-react-native/ios/STStorylyDataConverter.swift:19:31: value of optional type 'URL?' must be unwrapped to refer to member 'absoluteString' of wrapped base type 'URL'

        "iconUrl": storyGroup.iconUrl.absoluteString,

**Comment by levent-oral** [comment]
Hello @yasinugrl ,

We've released [storyly-react-native@1.29.1](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#1291-10012023) to address this issue. 

Thanks,
