### ISSUE TITLE
iOS crash 1.26.2

### ISSUE THREAD

**Issue by frabarbo** [Netvent/storyly-mobile#258]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

tracked on Google Analytics

## Environment Details
**Storyly SDK Version:** 1.26.2
**iOS SDK Version:** from iOS 15.6
**Device Model:** iPhone 13 Pro

## Expected Behavior
no crash

## Current Behavior
crash

Crashed: com.apple.main-thread
EXC_BREAKPOINT 0x0000000107dba034

Crashed: com.apple.main-thread
0  Storyly                        0x62034 <name omitted> + 203744 (__hidden#8336_:203744)
1  Storyly                        0x85500 <name omitted> + 348332 (__hidden#3551_:348332)
2  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
4  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
5  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
6  CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
7  CoreFoundation                 0x7c058 __CFRunLoopRun + 2036
8  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
9  GraphicsServices               0x1368 GSEventRunModal + 164
10 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
11 UIKitCore                      0x3a2034 UIApplicationMain + 340

**Comment by hmelihf** [comment]
Hello @frabarbo,

We've improved the codebase to address this issue in [Storyly iOS SDK@1.30.2](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1302-10022023). Please update and check the results. Let us know if the issue persists.

Thanks,
