### ISSUE TITLE
iOS crash on 1.29.0

### ISSUE THREAD

**Issue by nboliv** [Netvent/storyly-mobile#263]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

This crash happens as soon as a story is dismissed. Tracked on Firebase Crashlytics.

## Environment Details
**Storyly SDK Version:** 1.29.0
**Device Model:** iPhone
**Device OS Version:** Mostly iOS 16.X (86%) and iOS 15.X (13%) 

## Expected Behavior

No crash
## Current Behavior

Crash
## Stack Trace

Crashed: com.apple.main-thread
0  Storyly                        0xf8364 _hidden#7916_ + 949456 (__hidden#8269_:949456)
1  Storyly                        0x2c724 _hidden#4716_ + 114832 (__hidden#3679_:114832)
2  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
4  libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
5  libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
6  CoreFoundation                 0x9a6f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
7  CoreFoundation                 0x7c058 __CFRunLoopRun + 2036
8  CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
9  GraphicsServices               0x1368 GSEventRunModal + 164
10 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
11 UIKitCore                      0x3a2034 UIApplicationMain + 340

**Comment by levent-oral** [comment]
Related to [#258](https://github.com/Netvent/storyly-mobile/issues/258)

**Comment by nboliv** [comment]
Hello @hmelihf!
Yes, absoluteIy. I sent an email yesterday to some Storyly developers (copied Sahin on this email) with a full report of this crash, includind the .crash file, video evidence and Firebase stack straces.
If you wish, I can check if I can forward this email to you. 
Can you to share with me your company e-mail, please ? 
Thanks,
Nicolas

**Comment by hmelihf** [comment]
Hello @frabarbo,

We've improved the codebase to address this issue in [Storyly iOS SDK@1.30.2](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1302-10022023). Please update and check the results. Let us know if the issue persists.

Thanks,
