### ISSUE TITLE
Cannot compile project using Xcode 14.3 (beta)

### ISSUE THREAD

**Issue by daniel-tavares-nl** [Netvent/storyly-mobile#268]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

We are getting the below error when importing storyly via spm using Xcode 14.3

**Failed to build module 'Storyly'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', while this compiler is 'Apple Swift version 5.8 (swiftlang-5.8.0.119.11 clang-1403.0.22.11.100)'). Please select a toolchain which matches the SDK.**

## Environment Details
**Storyly SDK Version:** 1.31.4
**iOS SDK Version:** 16.4

## Expected Behavior

Project compiles

## Current Behavior

Errors during compilation

## Steps to Reproduce

1. Import storyly via spm
2. Using Xcode 14,3 beta try to compile

**Comment by levent-oral** [comment]
Hello @daniel-tavares-nl ,

We are using Xcode 13.4.1 version to build [Storyly iOS SDK](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1310-22022023). We also enable `BUILD_LIBRARY_FOR_DISTRIBUTION` to enable ABI stability for backward and forward compatibility. We're testing Xcode 14 versions as well. 

The error indicates that there could be breaking API change with Swift 5.8 which is bundled in Xcode 14.3 beta. 

Can you check with other versions of Xcode to ensure that this is the case? 

Thanks,

**Comment by daniel-tavares-nl** [comment]
Hey, thanks for response. Compiles fine on Xcode 14.2

**Comment by levent-oral** [comment]
We'll consider updating Xcode 14 version to build Storyly iOS SDK but backward compatibility related concerns and support for other platforms(ReactNative, Flutter and Xamarin) may be blocker for that. 

Please consider using Xcode 14.2 for Storyly iOS SDK.

Thanks,
