### ISSUE TITLE
Swift naming conventions for enums

### ISSUE THREAD

**Issue by bkunat** [Netvent/storyly-mobile#286]
Issue tracker is **ONLY** used suggestions.

`StorylyEvent` enum does not follow Swift guidelines for enum cases. Id appreciate if you could fix this.

```swift
// WRONG
case StoryGroupOpened
case StoryGroupUserOpened
case StoryGroupDeepLinkOpened

// RIGHT
case storyGroupOpened
case storyGroupUserOpened
case storyGroupDeepLinkOpened
```

**Comment by bkunat** [comment]
Reference: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/

**Comment by levent-oral** [comment]
Hello @bkunat ,

Thanks for suggestion!

[Swift's API Design Guidelines' General Convention](https://www.swift.org/documentation/api-design-guidelines/#conventions) sections indicates a general rule for case conventions;
> Follow case conventions. Names of types and protocols are UpperCamelCase. Everything else is lowerCamelCase.

That suggestion, starting with lower case, is the convenient way in terms of styling.

However, we need to consider backward compatibility for the current user base before refactoring any public APIs. In this case, this will have a considerably huge impact on the integration part for the update scenario, we don't consider any change for now. 

Thanks,
