### ISSUE TITLE
`StorylySegmentation` isDynamicSegmentationEnabled doesn't exist.

### ISSUE THREAD

**Issue by daniel-tavares-nl** [Netvent/storyly-mobile#288]
Hi,

I was following the documentation (https://integration.storyly.io/ios/segmentation.html#passing-segments-to-storyly-sdk) and I cannot find the `isDynamicSegmentationEnabled` in the sdk

```swift
StorylySegmentation(segments: Set<String>,
                    isDynamicSegmentationEnabled: Bool,
                    dynamicSegmentationCallback: StorylyDynamicSegmentationCallback?)
 ```

## Environment Details
**Storyly SDK Version:** 1.32.6

**Comment by levent-oral** [comment]
Hello @daniel-tavares-nl and @lupsyn ,

We've removed dynamicSegmentatiok feature earlier versions of Storyly SDKs.Moreover, we've moved our documentation.

Please refer [Android Targeting: User Segments](https://docs.storyly.io/docs/android-targeting) and [iOS Targeting: User Segments](https://docs.storyly.io/docs/ios-targeting).

Thanks!
