### ISSUE TITLE
SPM or Carthage

### ISSUE THREAD

**Issue by burakyilmaz50** [Netvent/storyly-mobile#29]
I want to install with SPM or Carthage. What should I do? It can also be locally.

**Comment by levent-oral** [comment]
Hi @burakyilmaz50 ,

We're currently supporting CocoaPods only, not supporting SPM or Carthage. Can you elaborate local support for this package managers so that we can help you on this?

**Comment by burakyilmaz50** [comment]
@levent-oral Greetings Levent Bey, what kind of support do you want?

**Comment by levent-oral** [comment]
@burakyilmaz50 greetings :) 

What do you mean by 'locally', my understanding is that you can create related file(package.swift or cartage file) on local to access and import Storyly SDK? Is this correct?  If so, what do you need on our side to support local import from SPM or Carthage?

**Comment by burakyilmaz50** [comment]
@levent-oral 
After I download sdk from GitHub and add it to my own project directory, I want to import it. However, I am having problems with this on SDWebImage. We would appreciate it if you bring SPM support or Carthage support. How can I add manually if you can't?
