### ISSUE TITLE
[Android] Storyly View as a composable view

### ISSUE THREAD

**Issue by mike192** [Netvent/storyly-mobile#290]
Is it planned to introduce Storyly View as a composable view in the SDK? 

Currently, on our site, all new features use Jetpack Compose, and introducing _AndroidComposeView_ instance for interoperability adds a redundant layer of logic.

**Comment by SancakKadir** [comment]
Hi @mike192,
Thanks for the suggestions! :tada:
Storyly SDK can be used in Jetpack compose projecsts using [Jetpack Compose's Interoperability APIs](https://developer.android.com/jetpack/compose/migrate/interoperability-apis), please check [StorylyJetpackCompose Demo](https://github.com/Netvent/storyly-mobile/tree/master/android/kotlin/StorylyJetpackCompose) project. Moreover, we don’t have any plan to make Storyly composable.
Thanks!

**Comment by mike192** [comment]
Thanks for the answer.

**Comment by wrozwad** [comment]
+1 for Composable view :)
