### ISSUE TITLE
Storyly SDK Layout Breaks on Orientation Change

### ISSUE THREAD

**Issue by bkunat** [Netvent/storyly-mobile#291]
My mobile application supports both landscape and portrait modes, allowing users to seamlessly switch between orientations. However, I have encountered an issue with the Storyly SDK, as it fails to adapt to the changes in orientation gracefully. When users switch from portrait to landscape mode or vice versa, the Storyly layout becomes distorted or misaligned, resulting in a broken user experience.

## Environment Details
**Storyly SDK Version:** 1.32.5
**iOS SDK Version:** Xcode 14.1
**Device Model:** iPad Air 2
**Device OS Version:** 14.0.1
**Additional Info:** This issue is reproducible on other devices. I've also tried iPad 9th generation iOS 15.5.

## Expected Behavior
Storyly SDK should adapt when the device orientation changes.

## Current Behavior
Storyly SDK breaks when the orientation changes when a story group is opened.

## Steps to Reproduce

1. Open a story group
2. Change device orientation when playing stories. At some point the layout will break.

Here's a demo: 
https://youtu.be/DXwFmrun0eU

I couldn't upload it here because of attachment size limit.

**Comment by bkunat** [comment]
We've updated the SDK to the latest version. This issue still exists in 2.1.0.

**Comment by yigcal** [comment]
Hello @bkunat ,

We've released [Storyly iOS SDK 2.3.1](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#231-22092023). We've fixed the layout on orientation changes.

Thanks
