### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Storyly"

### ISSUE THREAD

**Issue by jorgeestebancl12** [Netvent/storyly-mobile#309]
Error pod install with version 2.3.0, no work.

```
"react": "18.2.0",
"react-native": "0.71.4",
```

<img width="1094" alt="Screenshot 2023-09-14 at 3 41 42 PM" src="https://github.com/Netvent/storyly-mobile/assets/13371695/c248432d-c07b-49be-b740-5078ff9cf793">

**Comment by levent-oral** [comment]
Hello @jorgeestebancl12 ,

We've increased minimum deployment target to iOS 11 with [storyly-ios-sdk@2.2.0](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#220-23082023).  This storyly-ios-sdk version is bundled with [storyly-react-native@2.2.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#220-24082023) and further versions. 

Please update deployment target from Podfile of the project or you can use earlier versions of storyly-react-native.

Thanks,
