### ISSUE TITLE
Flutter Moments

### ISSUE THREAD

**Issue by rlee1990** [Netvent/storyly-mobile#311]
Will moments support be coming to flutter any time soon?

**Comment by levent-oral** [comment]
Hello @rlee1990 ,

Thanks for the interest about Storyly's Moments 🎉 

Moments' Flutter SDK is not in the current plans for now. Contributions are welcomed! :) You can check [storyly-mobile/moments](https://github.com/Netvent/storyly-mobile/tree/master/moments) samples for ios/android and integration for react-native to understand scope for Flutter as well. Moreover, [Moments' Android SDK Documentation](https://docs.storyly.io/docs/moments-android-quick-start), [Moments' iOS SDK Documentation](https://docs.storyly.io/docs/moments-ios-quick-start) and [Moment's React-Native SDK Documentation](https://docs.storyly.io/docs/moments-react-native-quick-start) can guide you about the integration. 

Thanks,
