### ISSUE TITLE
Tracking Total Watch Time in Session

### ISSUE THREAD

**Issue by bkunat** [Netvent/storyly-mobile#315]
Hello there!

We are currently using Storyly 2.1.0 SDK and are interested in tracking the amount of time a unique user spends watching stories during a specific session. Here's our current approach:

We have identified various events that are triggered when stories are closed, including events such as StoryGroupClosed, StoryGroupCompleted, and StoryCTAClicked. Within each of these events, we calculate the total watch time by summing up the .currentTime values from all the stories within a particular group.

We're curious if there might be a more efficient or optimal method for obtaining the total watch time metric. Any insights or suggestions would be greatly appreciated!

**Comment by yigcal** [comment]
Hi @bkunat ,

The events you selected to indicate the end of the session are correct. However, if your user visits a story multiple times, you only get the latest watch time with these events. So, it is better to check StoryNextClicked, StoryGroupNextSwiped, StoryGroupPreviousSwiped, StoryPreviousClicked and StoryCompleted events in storylyEvent callback and sum up the currentTime, then finish the session when storylyStoryDismissed callback is triggered. This way would be more accurate.

Thanks
