### ISSUE TITLE
Stories are not more clickable in minified build.

### ISSUE THREAD

**Issue by lupsyn** [Netvent/storyly-mobile#321]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version:** 1.34.0---
**Android SDK Version:** API 34---
**Device Model:** Also on the emulator (pixel 7(---
**Device OS Version:** ---
**Additional Info:** Proguard enabled---

## Expected Behavior
Clicking on storyly views should always work

## Current Behavior
When i tap on a story, and later on closing the full content view, the same story, as well as the others aren't clickable.
It seems something due progurad, or some listener which isn't reset.

## Steps to Reproduce

1. Enable proguard / minified + shrinked version
2. Create storyly view with content (more than one tappable story)
3. Open the content, and dismiss the full story
4. You can see all other stories aren't clickable

**Comment by Sultan1993** [comment]
Experiencing the same issue. It is present on version 2.4.0, 2.5.0 and the latest 2.5.1.
Target and compile SDKs are set to 34.

**Comment by yigcal** [comment]
Hi @lupsyn  and @Sultan1993 ,

We’ve fixed this issue with [Storyly Android SDK@2.5.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#252-16112023). Please update and check the results. Let us know if the issue persists.

Thanks
