### ISSUE TITLE
[2.5.1] Android build error

### ISSUE THREAD

**Issue by AuroPick** [Netvent/storyly-mobile#324]
I want to upgrade package version from `1.33.1` to `2.5.1`. After upgrading the version I started to getting this errors on Android build.

![image](https://github.com/Netvent/storyly-mobile/assets/53499802/8af3830d-dbb5-4a32-a7c2-599e57c65096)

```zsh
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':storyly-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

```

## Environment Details
**Storyly SDK Version:** 2.5.1
**React Native SDK Version:** 0.72.6
**Platform:**
- [x] Android 
- [ ] iOS
**Device Model:** --
**Device OS Version:** ---
**Additional Info:** 

Gradle 8.0.1

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.9 (Azul Systems, Inc. 17.0.9+8-LTS)
OS:           Mac OS X 13.0.1 aarch64

## Expected Behavior

Build should be successful

## Current Behavior

Android build error

## Steps to Reproduce

1.
2.
3.
4.

**Comment by yigcal** [comment]
Hi @AuroPick,

storyly-react-native package is migrated to Fabric in [v2.5.0](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#250-10102023). Please use the [legacy versions](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native-legacy/RELEASENOTES.md) if you have not supported Fabric, yet. Please check and let us know if your problem persists.

Thanks
