### ISSUE TITLE
Pod Compatibility Issue

### ISSUE THREAD

**Issue by karakusnavy** [Netvent/storyly-mobile#344]
## Environment Details
**Storyly SDK Version:** 2.4.9
**iOS SDK Version:** 17.2
**Device Model:** Apple M2 Pro
**Device OS Version:** 14.2
**XCode:** 15.2

## Expected Behavior
The iOS application should launch successfully after installing the Storyly package and pods.

## Current Behavior
After installing the Storyly package and pods in our React Native application, the iOS application fails to launch. This is due to compatibility issues between the latest version of Xcode (15.2) and Storyly.

## Steps to Reproduce
1. Install the Storyly package to a React Native application.
2. Install pods.
3. Attempt to launch the iOS application.

After installation, the iOS application fails to launch due to compatibility issues between Xcode 15.2 and Storyly.

Additional notes: The issue can be resolved temporarily by manually changing the text `DT_TOOLCHAIN_DIR` to `TOOLCHAIN_DIR` in certain files, as depicted in the provided screenshot. However, this manual intervention complicates our devops processes and necessitates a permanent fix for the situation.
<img width="1207" alt="image" src="https://github.com/Netvent/storyly-mobile/assets/29973831/9b342968-3290-49dd-9ed2-e239c82f80e6">

**Comment by yigcal** [comment]
Hi @karakusnavy,

Cocoapods fixed this problem with version 1.13.0 as stated here:
https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0
So, updating the cocoapods version to >= 13.0.0 will solve the issue.

Thanks
