### ISSUE TITLE
Dismiss button or Swipe to Dismiss not working if User pressed Action button and opened URL

### ISSUE THREAD

**Issue by DmtrPonomarenko** [Netvent/storyly-mobile#345]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

Dismiss button or Swipe to Dismiss not working if User pressed Action button and opened URL

Users can't close Storyly becasue of infinity loop

## Environment Details
**Storyly SDK Version:** --- 2.12.1 (2.13 the same)
**iOS SDK Version:** --- 
**Device Model:** --- any
**Device OS Version:** --- 17.2, 17.1
**Additional Info:** ---

## Expected Behavior

User should have ability to close Storyly by press X button or Swipe to dismiss

## Current Behavior

User can't close Soryly

## Steps to Reproduce

1. Open story with Action Link Button
2. Open browser Page
3. Return to app
4. Story can't be closed - reopen every time when user trying to dismiss it

**Comment by SancakKadir** [comment]
Hello [DmtrPonomarenko](https://github.com/DmtrPonomarenko) ,

We couldn't reproduce the issue. We  have a few questions to understand the issue;

- Can you share a video in order to see the steps of the issue?
- How do you handle action url?
- Do you use any StorylyView functions such as resumeStory, pauseStory, closeStory in this flow if so could you tell us in which step do you use?

**Comment by hmelihf** [comment]
Hi @DmtrPonomarenko,

When a view controller is presented modally over a StorylyViewController, everything functions as expected. However, we encountered the issue when a view controller is not presented modally over a StorylyViewController, such as in fullscreen presentationStyle. We intend to address this issue with the upcoming SDK update.

Thanks

**Comment by hmelihf** [comment]
Hi @DmtrPonomarenko,

We've released [Storyly iOS SDK 2.17.1](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#2171-24042024). We've improved the codebase to prevent this issue. Let us know if the issue persists.

Thanks
