### ISSUE TITLE
The dismiss callback is happening before the storyly screen closes

### ISSUE THREAD

**Issue by margarote** [Netvent/storyly-mobile#359]
Issue tracker is **ONLY** used for reporting iOS SDK related bugs.

## Environment Details
**Storyly SDK Version:** --- 2.5.1
**iOS SDK Version:** --- 
**Device Model:** ---
**Device OS Version:** ---
**Additional Info:** ---

## Scenario:
We needed to open a native IOS route in Flutter when the user clicked on the button within the storyly it closed, and tried to open the native route

## Problem:
The problem is that when we try to open the native route, it does not open, because at the moment it is closing the storyly, it emits the dismiss event, which is not true and this ends up closing the storyly and the native route that I I was trying to open

## Solution:
We need to trigger a real event when the storyly screen actually closes, so we have a more true dismiss event, and this way we can reduce these problems

**Comment by hmelihf** [comment]
Hello @margarote ,

We’ve fixed this issue with [storyly_flutter@2.18.0](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/CHANGELOG.md#2180-13052024). Please update and check the results. Let us know if the issue persists.

Thanks,
