### ISSUE TITLE
Invariant Violation: requireNativeComponent: "STStoryly" was not found in the UIManager.

### ISSUE THREAD

**Issue by supagu** [Netvent/storyly-mobile#37]
I just followed the install instructions here to add Storyly to my react-native project:
https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native

First I did: npm install --save storyly-react-native

Added the line: 
`import { Storyly } from 'storyly-react-native';`

Then in my render method added the component:

`<Storyly
          style={{ width: '100%', height: 120 }}
          storylyId="{token for my app is here}"
          onLoad={storyGroupList => {
            console.log("Storyly.onLoad");
          }}
          onFail={errorMessage => {
            console.log("Storyly.onFail");
          }}
          onPress={story => {
            console.log("Storyly.onPress");
          }}
          onStoryOpen={() => {
            console.log("Storyly.onStoryOpen");
          }}
          onStoryClose={() => {
            console.log("Storyly.onStoryClose");
          }}
        />`

trying to run the app I get:
![Screen Shot 2020-11-10 at 4 45 49 pm](https://user-images.githubusercontent.com/11153232/98635313-ab2d8e00-2374-11eb-80e4-f3022430351b.png)

**Comment by levent-oral** [comment]
Hi @supagu,

This seems that an issue related with linking Storyly package to library.

Can you ensure that you've completed 'Linking Library' part of [Getting Started section](https://github.com/Netvent/storyly-mobile/tree/master/react-native/storyly-react-native#getting-started)?

Moreover, can you ensure that you've run 'pod update' inside project's ios folder? 

Thanks,

**Comment by supagu** [comment]
okay a "pod update" did the trick, but now I have a compile problem it seems:
![Screen Shot 2020-11-11 at 9 13 09 am](https://user-images.githubusercontent.com/11153232/98742340-3010ba00-23fe-11eb-8161-9e074accdcbe.png)

**Comment by levent-oral** [comment]
Hi @supagu,

We've released storyly-react-native 1.8.2 version. This issue should be fixed. Please update to latest version and run 'pod update' inside project's ios folder as well.

Thanks,

**Comment by supagu** [comment]
Okay some progress, it now builds but I seem to get an error when running:
![Uploading Screen Shot 2020-11-12 at 2.02.02 pm.png…]()

**Comment by piotrpoz** [comment]
Same here, a runtime error:

```
dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: /CoreSimulator/Devices/F6A3E7FE-40FF-437B-A941-F6990F23D5A3/data/Containers/Bundle/Application/B737ED50-52DE-4A38-9B75-5711A52CBF98/Thriver.app/Frameworks/Storyly.framework/Storyly
  Reason: image not found
dyld: launch, loading dependent libraries
```

Using:
storyly-react-native: 1.8.3, 
react-native: 0.63.3,
react: 16.13.1

**Comment by levent-oral** [comment]
You need to add 'use_frameworks!' in application's ios package's Pods file as in [Storyly ReactNative Demo](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/StorylyDemo/ios/Podfile#L1).

Moreover, @supagu, please make sure that react-native version is 0.61+ for better CocoaPods support as it's mentioned [ReactNative Release Notes](https://github.com/facebook/react-native/releases/tag/v0.61.0)

**Comment by piotrpoz** [comment]
@levent-oral Thanks for the answer, unfortunately, adding `use_frameworks!` leads to `pod install` failure with the following error:

```
The 'Pods-APPNAME' target has transitive dependencies that include statically linked binaries
```

**Comment by SPLAYER-HD** [comment]
I have the same problem,

`dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: /private/var/containers/Bundle/Application/795C42FD-F08E-4C37-9D32-70883D320016/app.app/Frameworks/Storyly.framework/Storyly
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
(lldb) `

If I add use_frameworks! I get in the same problems as @piotrpoz.
I tried to change linked binaries, but I couldn't change all of them, so It's necessary to fix this bug, please.

**Comment by levent-oral** [comment]
i want to suggest adding a pre_install script to enhance Storyly import process.

please merge following lines to ios projects Podfile;

`
podfile suggestions=
dynamic_frameworks = ['Storyly', 'SDWebImage'] # <- swift libraries names

# Make all the other frameworks into static frameworks by overriding the static_framework? function to return true
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name)
      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.static_framework?;
        true
      end
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end
`

this will affect only Storyly related libraries to be compiled as dynamic framework instead of all of them in `use_frameworks !` usage.

**Comment by piotrpoz** [comment]
@levent-oral  I've downloaded latest storyly, cleaned up the pods and reinstalled them after updating Podfile as you've suggested (although I had to change the if condition by removing negation as it was working the opposite). After this, when building the app I get following errors:

`Cannot find protocol declaration for 'StorylyDelegate'; did you mean 'NSPortDelegate'?` in storyly-react-native/STStorylyView.h:16
`@interface STStorylyView : UIView <StorylyDelegate>`

![Screenshot 2020-12-04 at 15 14 21](https://user-images.githubusercontent.com/5487682/101167974-68916580-3643-11eb-86f2-82d7b41d0ba5.png)

**Comment by SPLAYER-HD** [comment]
Thank you @levent-oral that works for me.

I share my podfile:

```
use_frameworks!
platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

dynamic_frameworks = ['Storyly', 'SDWebImage', 'KumulosSdkObjectiveCExtension', 'KumulosKSCrash', 'KumulosSdkObjectiveC']

  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if !dynamic_frameworks.include?(pod.name)
        puts "Overriding the static_framework? method for #{pod.name}"
        def pod.static_framework?;
          true
        end
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```

**Comment by levent-oral** [comment]
We've updated documentation [Storyly React Native package iOS Installation](https://integration.storyly.io/react-native/quick-start.html#ios-installation), please check that.

Quick note from there; (thanks to @SPLAYER-HD as well 🎉 ) you need to add following lines to Podfile;
