### ISSUE TITLE
Cannot find protocol declaration for 'StorylyDelegate'

### ISSUE THREAD

**Issue by piotrpoz** [Netvent/storyly-mobile#39]
Trying to build iOS Release version of react native app with Storyly.

storyly-react-native: 1.8.3,
react-native: 0.63.3,
react: 16.13.1

While building, I am getting following error:
```
Cannot find protocol declaration for 'StorylyDelegate'; did you mean 'NSPortDelegate'?
```
![Screenshot 2020-11-12 at 18 05 57](https://user-images.githubusercontent.com/5487682/98964685-c97cc080-2511-11eb-924c-bcc73dc348d2.png)

Not sure why it selects "Development Pods" instead of "Pods". I am using default settings.
Note: debug build crashes runtime, described here: https://github.com/Netvent/storyly-mobile/issues/37#issuecomment-726160808

Any help much appreciated!

**Comment by inveon-yakupdurmus** [comment]
Aynı problem

"storyly-react-native": "^1.8.4",
"react": "16.9.0",
"react-native": "0.61.2",

**Comment by inveon-yakupdurmus** [comment]
cocoapods'u güncelledikten sonra  düzeldi
```
sudo gem install cocoapods --pre
npm install 
pod install --repo-update
```
güncell pod versiyonum : 1.10.0

**Comment by levent-oral** [comment]
We've updated documentation [Storyly React Native package iOS Installation](https://integration.storyly.io/react-native/quick-start.html#ios-installation), please check that.

Quick note from there; you need to update your CocoaPods version to 1.9+ to support xcframework usage.
