### ISSUE TITLE
Test-Flight (Non App Store) apps, bundle id is not accepted

### ISSUE THREAD

**Issue by dustfire** [Netvent/storyly-mobile#4]
Hey guys, another question. Your admin panel errors out saying "Bundle id not found".
Possible to integrate the Storyly to a non-released/upcoming product?

<img width="604" alt="Screen Shot 2020-01-29 at 11 20 45 AM" src="https://user-images.githubusercontent.com/13444100/73375187-6cb55f80-4289-11ea-8194-c1052c25dbf4.png">

**Comment by levent-oral** [comment]
This issue is related with Dashboard, question has been escalated to team and it will be done.
