### ISSUE TITLE
Storyler yüklenirken Storly Containerı simsiyah görünüyor

### ISSUE THREAD

**Issue by memreakyl** [Netvent/storyly-mobile#40]
Issue tracker is **ONLY** used for reporting Flutter SDK related bugs.

## Environment Details
**Storyly SDK Version:** ^1.8.4
**Flutter SDK Version:** 1.22.3
**Platform:**
- [x] Android
- [ ] iOS
**Device Model:** Pixel 3A XL (Emulator, ama gerçek telefonlarda da var aynı sorun)
**Device OS Version:** API 30
**Additional Info:** StorylyView her yüklendiğinde şu hata geliyor:
E/ThemeUtils( 5135): View class a.a.a.l.f.e is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
## Expected Behavior
Beklenen davranış StorylyView build’e girdikten sonra yükleme sırasında, arka planla aynı renk üzerine yüklenmesi.
## Current Behavior
StorylyView build’e girdiği zaman önce siyah bir ekran geliyor, sonra üzerine yükleniyor. Genellikle bu siyah ekran görülmeyecek kadar hızlı bir şekilde geçiyor ama uygulama yeterince ağırsa farkedilecek kadar uzun sürebiliyor.
## Steps to Reproduce
StorylyView bulunan sayfada, Android Studio’nun Hot Reload özelliği ile uygulamayı sürekli yenileyince siyah ekran en basit hali ile görülebilir. Bizim uygulamamızda sorun şu durumlarda olmaktadır:
1.	TabBarView’da Tab’lar arası geçiş yapılınca siyah ekran gözükebiliyor. Ayrıca tablar arasında geçiş yapıldığında her seferinde storyLoaded yeniden çalışıyor bunun sebebini sorabilir miyim, flutter'la ilgili bir durum mudur?
https://imgflip.com/gif/4o13sr
2.	Uygulama ilk açıldığında Storyly Offstage sınıfı altında saklı ve genişliği değişken bir Container içinde geliyor. storylyLoaded fonksiyonu ile görünmezlik kaldırılınca ve genişlik değeri belirlenince StorylyView siyah ekran üzerine yükleniyor. Benzer durumu sıfırdan bir uygulamada elde edemedim.
https://imgflip.com/gif/4o1476

**Comment by levent-oral** [comment]
Selam @memreakyl,

Hatayi reproduce edebilmemiz ve detaylarini anlayabilmemiz icin gerekli alanlari doldurabilir misin?

Tesekkurler,

**Comment by memreakyl** [comment]
Selam @levent-oral, 

Issue'yu editledim detaytları bulabilirsin.

İyi çalışmalar

**Comment by levent-oral** [comment]
Selam @memreakyl, 

Flutter Example App'inde soyle bir degisiklik yaparak hatayi olusturmayi denedik, fakat siyah bir arka plan goremedik. Hatanin sebebini anlayabilmemiz icin bir oneride bulunabilir misin? Offstage kullanimi veya senin tarafinda etkiledigini dusundugun baska bir kismi belirtirsen onunla hatayi olusturmayi deneyebiliriz.

```
bool _offstage = true;

child: Offstage(
  offstage: _offstage,
  child: StorylyView(
      ...
      storylyLoaded: (storyGroupList) {
        print("storylyLoaded");
        setState(() {
          _offstage = false;
        });
      },
      ....
))
```

Ayni sekilde ThemeUtils hatasini loglarda gozlemledik, o nedenle su an onunla ilgili olmadigini dusunuyoruz.

TabBarView kullaniminda, her tab gecisinde view bastan olusturuluyorsa `storylyLoaded` eventi gelmesi normaldir.

Tesekkurler,

**Comment by dikkat** [comment]
Selam @levent-oral 

Emre bey adına ben bakıyorum bu meseleye. Flutter Example App'te bizdeki sisteme benzer bir yapı kurmaya çalıştım. Example App yeterince ağır değil, o yüzden belleğe yüklenerek sistemi olabildiğince yavaşlattım. Sonuç olarak vereceğim kod ile 2-3 yenilemede(hot restart ile) 1 kez denk gelecek sıklıkta siyah ekran yakalayabildim. Ama bu ekran bizim uygulamadakine göre çok daha az kalıyor, farkedilmeyecek kadar. Ve eğer sistem boştaysa çok daha nadir geliyor. O yüzden repro etmesi bayağı zor. Ama bizim uygulamada her açılışta kesin geliyor ve Example App'tekinden çok daha uzun sürüyor.

Sekme geçişlerinde yeniden yüklenmesini engelleyerek sekmeler arası geçişteki siyah ekranı çözdük. Şuan tek sıkıntı başlangıçta gelmesi.

[Example App Gif](https://imgflip.com/gif/4pj032)

[Example App Kod](https://glot.io/snippets/ftsf42f35h/raw). Bizim uygulamaya benzer ama basitleştirilmiş hali, bu haliyle de siyah ekran görülebiliyor. ID kısmını boş bıraktım, içinde hikaye olan herhangi ID işe yarar diye düşünüyorum, olmazsa isterseniz bizdeki ID'yi atabilirim. 

pubspec.yaml'a eklemek için:
`get_it: ^4.0.2`
`stacked: ^1.7.1+1`

**Comment by levent-oral** [comment]
Selam @dikkat ,

Kod paylasimi ve detaylar icin tesekkur ederim. Birden fazla telefon ve emulatorde denedim fakat olusturamadim. Emulatorde denedigimde video konferans toplantisindaydim, sistem bostayken olusturulmuyor yazdigin icin sistemi doldurmaya calistim diyeyim. 

Kendi tarafimizda [Example Offstage usage with Storyly](https://pastebin.pl/view/fdf8ced4) ile bir projede de denedik. Ayrica bir iki noktada StorylyView'in icinde bulundugu Container'e `color: Colors.cyan,` seklinde background ekledim. Boyle bir durumda 'siyah' yerine baska bir renk gorunur mu diye merak etmistim acikcasi. Theme bazli bir degisimin olabileceginden supheleniyorum, bu konudaki fikriniz nedir?

Kolay gelsin,

**Comment by levent-oral** [comment]
Flutter'da PlatformView kullaniminda, ozellike 'Hot Reload' asamasinda bahsedilen siyah ekran goruntusunun olusabildigini dair 'issue'lar soz konusu. Flutter tarafindaki guncellemeleri, degisiklikleri takipteyiz, herhangi bir guncelleme oldugunda uygulayacagiz. 

Tema ile alakali olusan baska bir durum icin [#49 ](https://github.com/Netvent/storyly-mobile/issues/49) takip edebilirsiniz.
