### ISSUE TITLE
Execution failed for task ':app:checkProductionDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by pratyesh** [Netvent/storyly-mobile#42]
* What went wrong:
Execution failed for task ':app:checkProductionDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class a.a.a.a found in modules jetified-paymentparamhelper-1.1.1-runtime (com.payu.paymentparamhelper:paymentparamhelper:1.1.1) and jetified-storyly-1.8.4-runtime (com.appsamurai.storyly:storyly:1.8.4)

We are having a library conflict with Payu & Storyly Sdk.

sdk details:-
implementation 'com.appsamurai.storyly:storyly:1.8.4'
//payu SDK
implementation 'com.payu.india:payu-checkout-pro:1.1.0'

Please help us to fix this issue. let me know if more details are required.

**Comment by levent-oral** [comment]
Hi @pratyesh,

We've able to reproduce the issue with our [Storyly Java Sample](https://github.com/Netvent/storyly-mobile/tree/master/android/java/StorylyDemo). We'll let you know for further details.

Thanks,

**Comment by JohannaTekinder** [comment]
Hi,

I have the same issue with another library:

`Duplicate class a.a.a.a found in modules jetified-netcheck-3.3.339.jar (:netcheck-3.3.339:) and jetified-storyly-1.8.4-runtime.jar (com.appsamurai.storyly:storyly:1.8.4)
`

**Comment by levent-oral** [comment]
Hi @JohannaTekinder ,

It seems that ProGuard usage in Kotlin projects has caused this. We'll try possible obfuscation configurations to prevent this happening due to Storyly.

Thanks,

**Comment by levent-oral** [comment]
We've released [1.8.5](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md) version to prevent this issue happening due to Storyly. 

@pratyesh , @JohannaTekinder , please update to this version.

Thanks,

**Comment by rajmaxi** [comment]
Hi,  I am also getting the same issue when i install  payu-non-seam-less-react..   

java.lang.RuntimeException: Duplicate class a.a.a.a found in modules jetified-paymentparamhelper-1.1.1-runtime.jar (com.payu.paymentparamhelper:paymentparamhelper:1.1.1) and jetified-payu-crash-logger-1.0.1-runtime.jar (com.payu.crashlogger:payu-crash-logger:1.0.1)

Please help us to fix this issue. let me know if more details are required.

**Comment by levent-oral** [comment]
@rajmaxi's comment: 

> Hi, I am also getting the same issue when i install payu-non-seam-less-react..

> java.lang.RuntimeException: Duplicate class a.a.a.a found in modules jetified-paymentparamhelper-1.1.1-runtime.jar (com.payu.paymentparamhelper:paymentparamhelper:1.1.1) and jetified-payu-crash-logger-1.0.1-runtime.jar (com.payu.crashlogger:payu-crash-logger:1.0.1)
> 
> Please help us to fix this issue. let me know if more details are required.
> 

@rajmaxi, can you confirm that you're using storyly-react-native, please?

we're updating storyly-react-native to latest version, we'll let you know from here as well.

**Comment by rajmaxi** [comment]
Hi, I am getting the same error  with implementation 'com.payu.india:payu-checkout-pro:1.1.0'

when i install "payu-non-seam-less-react": "^2.1.0",

Execution failed for task ':app:checkDebugDuplicateClasses'.
1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class a.a.a.a found in modules jetified-paymentparamhelper-1.1.1-runtime.jar (com.payu.paymentparamhelper:paymentparamhelper:1.1.1) and jetified-payu-crash-logger-1.0.1-runtime.jar (com.payu.crashlogger:payu-crash-logger:1.0.1)

Please help us to fix this issue.
