### ISSUE TITLE
Bottom space for two lines in the group name looks too much

### ISSUE THREAD

**Issue by SPLAYER-HD** [Netvent/storyly-mobile#45]
Hi Guys,

The Storyly has a big space in the bottom, I just realize that is for the group name when it has to use 2 lines using the 25 characters, but when any story group has 2 lines looks a little bit bad. 

Do you have some way to avoid this space when any story has 2 lines? 

<img width="614" alt="Screen Shot 2020-12-15 at 3 16 12 pm" src="https://user-images.githubusercontent.com/6402323/102170575-ca29bd80-3ee8-11eb-9c90-bf939d9343f3.png">
or what is your advice to work around this?

I am attaching an example, as you can see in the image under the group name looks too much.

**Comment by levent-oral** [comment]
There is no work around for this. We may suggest giving shorter titles to 'Story Group Title' from Dashboard to ensure appearing to be single line and arrange StorylyView's(the storyly group list) height in container to reduce area.

We've checked several cases for title alignment; align to top, center and bottom. We think that this is the best usage for UI/UX.
