### ISSUE TITLE
Storyly Section has black background for few devices

### ISSUE THREAD

**Issue by santoshg-moneytap** [Netvent/storyly-mobile#49]
The StorylyView is wrapped with a white Container. It works fine for many devices, but for few devices, it appears that a black background is shown instead.

## Environment Details
Redmi Note 8 Pro - Android 10 - MIUI 12.0.3, Oppo f9 pro
Flutter Version:  1.22.5
Storyly_flutter: ^1.8.6

## Expected Behavior
The Storyly should have white background on all devices.

## Current Behavior
Few devices have black background.

## Steps to Reproduce
Use one of the devices mentioned above and navigate to screen showing Storyly view

**Comment by levent-oral** [comment]
Hello @santoshg-moneytap,

We've observed that there is 'App based Dark Theme' option in some devices which causes app's theme to be overridden with system setting. This option can cause view's, not theme set, to be shown in system theme setting. In your case, Storyly can be forced to show in dark theme. Can you check with system settings and theme adjustments? If so, you can set StorylyView by wrapping it with another container. 

Thanks,

**Comment by santoshg-moneytap** [comment]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/70517398/107316770-5ad2e300-6abf-11eb-927a-d7f9a079683c.png">


Despite wrapping the Storyly view with white container, the issue still persists.

**Comment by levent-oral** [comment]
We've investigated the issue with several aspect; Flutter, PlatformView usage and Android themes. It seems that there is a known issue on Flutter's PlatformView usage, which is required to show native components from our side. We are watching related issues on Flutter to cover the issue.

When an update is done by Flutter related to Theme management, we'll adapt it accordingly.
