### ISSUE TITLE
Issues with getting started on Android and iOS

### ISSUE THREAD

**Issue by mohsinulhaq** [Netvent/storyly-mobile#5]
I installed the module, run `react-native link`, but I am still getting the following errors on running:

On android:
`node_modules/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt: (56, 5): 'receiveCommand' overrides nothing`

On iOS:
```
node_modules/storyly-react-native/ios/STStorylyView.m:22:45: error: 'initWithFrame:' is unavailable
        _storylyView = [[StorylyView alloc] initWithFrame:frame];
                                            ^
```

I'm on RN `0.59.10`

**Comment by levent-oral** [comment]
Hi @mohsinulhaq ,
Thanks for the feedback. 

We've released 0.0.19 version to fix this issue. It was related with a deprecated method from ReactNative. 

For iOS, please run `pod update`, to ensure latest version of Storyly is used from CocoaPods.
