### ISSUE TITLE
When customer use small capacity (small than 3G RAM) phone to view Storyly, the whole app must be crush when the story page have emoji. It seem there is a memory leak problem need Storyly side to check.

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#62]
When customer use small capacity (small than 3G RAM) phone to view Storyly, the whole app must be crush when the story page have emoji. It seem there is a memory leak problem need Storyly side to check.

Run Storyly SDK in our JDID APP: 
https://user-images.githubusercontent.com/58552069/110072026-1550bf80-7db8-11eb-9348-85a445ddc03a.mp4

Only run Storyly SDK demo, not in JDID APP:
![Issue four-App crush](https://user-images.githubusercontent.com/58552069/110072420-b8093e00-7db8-11eb-943b-dcc265fdb259.jpg)

https://user-images.githubusercontent.com/58552069/110072447-c2c3d300-7db8-11eb-8a5f-71124b27d599.mp4

**Comment by levent-oral** [comment]
We've done memory profiling of Storyly with several cases, including Fragment flow. There is no excessive memory usage that can cause this type of crash you've experienced. Moreover, we've tested using different devices including emulators with smaller memory capacity. We've not observed any crash in these cases. 

We've checked possible memory leak cases with LeakCanary library. We've found a small issue and fixed it. Please check with [Storyly Android SDK 1.9.3](url)

Please check attached images for memory profiling cases. 
![memory_profiling_2](https://user-images.githubusercontent.com/11808188/110253866-9026ff80-7f9d-11eb-9cd7-6c3fedbb7e84.png)

![memory_profiling_1](https://user-images.githubusercontent.com/11808188/110253864-8e5d3c00-7f9d-11eb-92c9-66cfca36b57f.png)

**Comment by levent-oral** [comment]
We've released a version to address crash with Emoji usage. Please check with [Storyly Android SDK 1.9.4](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#194).

Moreover, you need to add EmojiCompat on application side to use emoji features as expected. Please check [Android Installation's EmojiCompat related section](https://integration.storyly.io/android/quick-start.html#installation).
