### ISSUE TITLE
When customer to share story to Facebook channel via Storyly deep link feature, it will show the original code. 

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#68]
When customer to share story to Facebook channel via Storyly deep link feature, it will show the original code. 

<img width="245" alt="original code1" src="https://user-images.githubusercontent.com/58552069/110304631-c82e5100-8036-11eb-9b83-7b3df29a93fc.png">
<img width="242" alt="original code2" src="https://user-images.githubusercontent.com/58552069/110304642-ca90ab00-8036-11eb-8bca-8409e38b00f2.png">

**Comment by levent-oral** [comment]
We've fixed the issue.
