### ISSUE TITLE
Animation to hide and show Storyly

### ISSUE THREAD

**Issue by SPLAYER-HD** [Netvent/storyly-mobile#69]
Hi Guys,

I have a problem with Storyly 1.8.4 on Android using React Native 0.63.3. Storyly is inside an animation view, when the user scrolls up or down the animation shrinks the view and the app has a button to open it again expanding it, the code works fine in IOS, but in android only appears the first time when the animation view has the full height. Storyly has in height 100%, therefore it takes the height of the parent, so it looks like the Storyly component is not able to get the height during the animation in android.

I am attaching the source code, the video with the behaviour in android and ios.

Video Android:
https://www.loom.com/share/bc182f21b02a40f990eaace1564a4350
Video IOS:
https://www.loom.com/share/dc2cc35fdb1644bfa140fec49b52a558

I was testing the last version of Storyly 1.9.1 for React Native, but with this version, the animation works neither in IOS nor in Android. I remove the animation only to confirm that the <Storyly> component is no taking the height I set in styles, it does not matter the number or percentage, I assume that it always takes the default height. So as is no taking the height, the animation over height is not working, so the view disappears, but Storyly component never hides.

Source code example:
`if (!isStorylyOpen) {      
      Animated.timing(height, {
        toValue: 0,
        duration: 600,
        easing: Easing.bezier(0.47, 0.53, 0.37, 0.96),
      }).start();
      Animated.timing(paddingTop, {
        toValue: 0,
        duration: 600,
        easing: Easing.bezier(0.47, 0.53, 0.37, 0.96),
      }).start();
    } else {
      Animated.timing(height, {
        toValue: HEIGHT,
        duration: 600,
        easing: Easing.bezier(0.47, 0.53, 0.37, 0.96),
      }).start();
      Animated.timing(paddingTop, {
        toValue: PADDING_TOP,
        duration: 600,
        easing: Easing.bezier(0.47, 0.53, 0.37, 0.96),
      }).start();
    }

    return (
      <Animated.View
        style={{
          paddingTop: paddingTop,
          height: height,
          backgroundColor: "#fff",
        }}
      >
        <Storyly
          style={{
            height: "100%",
          }}
          storyGroupTextColor={Color.gray40}
          storyGroupIconBorderColorSeen={[Color.gray153, Color.gray153]}
          storyGroupIconBorderColorNotSeen={[Color.salmon, Color.salmon]}
          storyGroupSize="small"
          storylyId="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NfaWQiOjE3MjMsImFwcF9pZCI6MTMwMiwiaW5zX2lkIjoxMzM4fQ.zwLuDve2gYyeCxfU6g-kclnzXgjw59qoLyOo1JDXPDw"
          onPress={story => {
            
            let url = story.nativeEvent.media.actionUrl;
            tapLink({ navigation, token, url });
            
          }}
        />
      </Animated.View>
    );`

**Comment by levent-oral** [comment]
Thanks @SPLAYER-HD! 

We're checking this issue and we'll let you know about updates.

**Comment by levent-oral** [comment]
We've fixed iOS's animation issue in [1.9.2](https://github.com/Netvent/storyly-mobile/blob/master/react-native/storyly-react-native/RELEASENOTES.md#192). 

However, we couldn't reproduce the issue on Android side. We prepared a [StorylyDemo application](https://github.com/Netvent/storyly-mobile/tree/master/react-native/StorylyDemo) to check the case. Can you check it on there and try to reproduce as well? If there is a difference between your usage, feel free to open a PR so that we can reproduce the case.

Thanks!

**Comment by levent-oral** [comment]
@SPLAYER-HD, did you get a chance to look into this?

**Comment by SPLAYER-HD** [comment]
Hi @levent-oral,
I will test it tomorrow and I will let you know how it goes.
Thank you

**Comment by SPLAYER-HD** [comment]
Hi @levent-oral,
Version 1.9.2 works fine in both IOS and Android, the animation hides and shows Storyly perfect.
Thank you so much.
