### ISSUE TITLE
one crash that happen in Storyly SDK, one customer crashed 19 times.

### ISSUE THREAD

**Issue by charischung** [Netvent/storyly-mobile#70]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

There is one crash that happen in Storyly SDK, one customer crashed 19 times.

![crash](https://user-images.githubusercontent.com/58552069/112125878-da93b780-8bfe-11eb-9daa-4ff777ace01a.jpg)
![crash](https://user-images.githubusercontent.com/58552069/112126027-00b95780-8bff-11eb-8fea-6c8f72479b0f.jpg)

**Comment by levent-oral** [comment]
We've fixed this issue in [Android 1.9.5](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#195).
