### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by mehmetbilgin** [Netvent/storyly-mobile#8]
file: storyly-mobile/android/README.md
implementation ‘com.appsamurai.storyly:storyly:<latest-version>' 
should be
implementation 'com.appsamurai.storyly:storyly:<latest-version>'

and

<com.appsamurai.storyly.StorylyView
    android:id="@+id/storyly_view"
    android:layout_width="match_parent"
    android:layout_height=“120dp”/>
should be
<com.appsamurai.storyly.StorylyView
    android:id="@+id/storyly_view"
    android:layout_width="match_parent"
    android:layout_height="120dp"/>

**Comment by levent-oral** [comment]
Hi @mehmetbilgin,

We've fixed char typo's in readme file.

Thanks,
