### ISSUE TITLE
Issue array list “out of bounds exception” in SDK 1.10.0

### ISSUE THREAD

**Issue by charischung415** [Netvent/storyly-mobile#85]
**Storyly SDK Version: 1.10.0
**Android SDK Version: 1.10.0
In JD.ID app, the story floor is shown at 2 places, one is on homepage, one is on Feed channel page. We RnD also found there is 1 issue array list “out of bounds exception”. Please also help to check.

---java.lang.IndexOutOfBoundsException: Invalid index 7, size is 0
java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
java.util.ArrayList.get(ArrayList.java:308)
com.appsamurai.storyly.storylypresenter.k.invoke(StorylyGroupRecyclerView.kt:1)
com.appsamurai.storyly.storylypresenter.t.m(StorylyGroupView.kt:5)
com.appsamurai.storyly.storylypresenter.p0.invoke(StorylyGroupView.kt:7)
com.appsamurai.storyly.storylypresenter.storylyheader.b$b.onAnimationEnd(Animator.kt:1)
android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
android.view.Choreographer.doCallbacks(Choreographer.java:672)
android.view.Choreographer.doFrame(Choreographer.java:605)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
android.os.Handler.handleCallback(Handler.java:742)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:157)
android.app.ActivityThread.main(ActivityThread.java:5696)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by charischung415** [comment]
BTW, if it is possible that your tech team provide the dysm file of this SDK to me(I am from JDID tech team),  our developers could help to check also.

**Comment by charischung415** [comment]
BTW, is it possible that your tech team provide the dysm file of this SDK to me(I am from JDID tech team)? Our developers could help to check also.

**Comment by charischung415** [comment]
but this issue still happens in SDK 1.10.0, which means the issue has not been fixed in SDK 1.9.5, please check again.

**Comment by levent-oral** [comment]
@charischung415 , we're actively investigating this issue. We'll let you know. 

Is there a specific case you can mention how to reproduce this issue?

**Comment by charischung415** [comment]
Put the SDK in 2 places of one app, different pages.  Then users switches these 2 pages.

发件人: Levent ORAL ***@***.***>
发送时间: 2021年4月13日 14:20
收件人: Netvent/storyly-mobile ***@***.***>
抄送: Charis Chung钟楚欣 ***@***.***>; Mention ***@***.***>
主题: [来自外部的邮件]Re: [Netvent/storyly-mobile] Issue array list “out of bounds exception” in SDK 1.10.0 (#85)


@charischung415<https://github.com/charischung415> , we're actively investigating this issue. We'll let you know.

Is there a specific case you can mention how to reproduce this issue?

**Comment by levent-oral** [comment]
@charischung415 ,

We've made an improvement for this issue in [Android SDK 1.10.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1102). 

Because of we're unable to reproduce this issue in our demo apps so we've made possible scenario fixes deduced from stack trace. If the issue continues on your side, please provide a sample demo app by opening a PR(fork storyly-mobile and add a sample)to reproduce this issue with device informations and steps to reproduce with details.

**Comment by charischung415** [comment]
please upload 1.10.2 in GitHub and bintray. We need to download it. Thanks.

发件人: Levent ORAL ***@***.***>
发送时间: 2021年4月15日 17:07
收件人: Netvent/storyly-mobile ***@***.***>
抄送: Charis Chung钟楚欣 ***@***.***>; Mention ***@***.***>
主题: [来自外部的邮件]Re: [Netvent/storyly-mobile] Issue array list “out of bounds exception” in SDK 1.10.0 (#85)


@charischung415<https://github.com/charischung415> ,

We've made an improvement for this issue in Android SDK 1.10.2<https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1102>.

Because of we're unable to reproduce this issue in our demo apps so we've made possible scenario fixes deduced from stack trace. If the issue continues on your side, please provide a sample demo app by opening a PR(fork storyly-mobile and add a sample)to reproduce this issue with device informations and steps to reproduce with details.

**Comment by levent-oral** [comment]
@charischung415 , we've moved our library to MavenCentral in the light of recent announcements about jCenter.

You can find it from [Maven Central Repository Search](https://search.maven.org/artifact/com.appsamurai.storyly/storyly).
