### ISSUE TITLE
issue: arraylist

### ISSUE THREAD

**Issue by charischung415** [Netvent/storyly-mobile#86]
java.util.ArrayList.subListRangeCheck (ArrayList.java:989)
java.util.ArrayList.subList (ArrayList.java:979)
arrow_right
com.appsamurai.storyly.data.cache.a.a (ImageCacheManager.kt:88)
com.appsamurai.storyly.storylypresenter.storylyview.g.invoke (StorylyItemView.kt:10)
com.appsamurai.storyly.storylypresenter.storylyview.c$b.a (StorylyItemImageView.kt:2)
com.bumptech.glide.request.SingleRequest.a (SingleRequest.java:622)
com.bumptech.glide.request.SingleRequest.a (SingleRequest.java:575)
com.bumptech.glide.load.engine.j.a (EngineJob.java:158)
com.bumptech.glide.load.engine.j$b.run (EngineJob.java:424)
android.os.Handler.handleCallback (Handler.java:836)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:232)
android.app.ActivityThread.main (ActivityThread.java:6802)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1103)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:964)

**Comment by levent-oral** [comment]
@charischung415 ,

We've made an improvement for this issue in [Android SDK 1.10.2](https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1102). 

Because of we're unable to reproduce this issue in our demo apps so we've made possible scenario fixes deduced from stack trace. If the issue continues on your side, please provide a sample demo app by opening a PR(fork storyly-mobile and add a sample)to reproduce this issue with device informations and steps to reproduce with details.

**Comment by charischung415** [comment]
please upload 1.10.2 in GitHub and bintray. Thanks.

On Apr 15, 2021, at 17:06, Levent ORAL ***@***.***> wrote:

﻿

@charischung415<https://github.com/charischung415> ,

We've made an improvement for this issue in Android SDK 1.10.2<https://github.com/Netvent/storyly-mobile/blob/master/android/RELEASENOTES.md#1102>.

Because of we're unable to reproduce this issue in our demo apps so we've made possible scenario fixes deduced from stack trace. If the issue continues on your side, please provide a sample demo app by opening a PR(fork storyly-mobile and add a sample)to reproduce this issue with device informations and steps to reproduce with details.

**Comment by levent-oral** [comment]
@charischung415 , we've moved our library to MavenCentral in the light of recent announcements about jCenter.

You can find it from [Maven Central Repository Search](https://search.maven.org/artifact/com.appsamurai.storyly/storyly).

**Comment by charischung415** [comment]
@levent-oral 
Hi, yesterday we found the arraylist crash issue in SDK 1.10.2 (android), please check. 

---java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
java.util.ArrayList.get(ArrayList.java:413)
com.appsamurai.storyly.storylypresenter.f$b.afterChange(Delegates.kt:40)
kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
com.appsamurai.storyly.storylypresenter.f.setSelectedStorylyGroupIndex(StorylyGroupRecyclerView.kt)
com.appsamurai.storyly.storylypresenter.h$a.onAnimationEnd(Animator.kt:11)
android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313)
android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:928)
android.view.Choreographer.doCallbacks(Choreographer.java:705)
android.view.Choreographer.doFrame(Choreographer.java:637)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
android.os.Handler.handleCallback(Handler.java:751)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6816)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1567)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1455)
