### ISSUE TITLE
SDK 1.10.0 crash in no internet situation

### ISSUE THREAD

**Issue by charischung415** [Netvent/storyly-mobile#87]
https://user-images.githubusercontent.com/82194795/114980121-92df1380-9ebe-11eb-9133-552bde048dfc.mp4
Issue IOS SDK: 1.10.0

If there is no internet, the APP with SDK 1.10.0 will crash, if we use SDK 1.9.1, the APP will not crash.

**Comment by levent-oral** [comment]
Hello @charischung415 ,

We've fixed an issue for this scenario, [iOS SDK 1.10.1](https://github.com/Netvent/storyly-mobile/blob/master/ios/RELEASENOTES.md#1101). Please check it and let us know if the issue persists. 

Thanks,
